eclipse-sirius/sirius-components

docs/designsystem.adoc, src/common/__tests__/classnames.test.js, src/common/classnames.js, src/components/app/App.css, src/components/app/App.js, src/components/aside/Aside.css, src/components/aside/Aside.js, src/components/aside/__tests__/Aside.test.js, src/components/aside/__tests__/__snapshots__/Aside.test.js.snap, src/components/cards/Card.css, src/components/cards/Card.js, src/components/cards/__tests__/Card.test.js, src/components/cards/__tests__/__snapshots__/Card.test.js.snap, src/components/dashboard/DashboardView.css, src/components/dashboard/DashboardView.js, src/components/list/List.css, src/components/list/List.js, src/components/main/Main.css, src/components/main/Main.js, src/components/navbar/Navbar.css, src/components/navbar/Navbar.js, src/components/navbar/__tests__/Navbar.test.js, src/components/navbar/__tests__/__snapshots__/Navbar.test.js.snap, src/components/projects/ProjectSummaryCard.css, src/components/projects/ProjectSummaryCard.js
This commit will add the basic structure of the application starting
with the App component which defines the layout of the main parts
of the user interface (Navbar, Aside, Main).
A new component named Main defines the main area of the application
where the various pages will appear thanks to the router. In this main
part, the DashboardView will be used to display the content of the
dashboard. In order to do that, it will use a Card to display various
projects, the ProjectSummaryCard. This ProjectSummaryCard is created
using both the Card and List components.
Unit tests have also been contributed in order to prevent regressions.
Bug: https://github.com/eclipse/sirius-components/issues/4
=> Add the first version of the Dashboard

README.adoc, src/components/dashboard/__tests__/DashboardView.test.js, src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap, src/components/projects/listprojects/ListProjectsView.js, src/components/projects/listprojects/__tests__/ListProjectsView.test.js, src/components/projects/listprojects/__tests__/__snapshots__/ListProjectsView.test.js.snap, src/components/projects/project/ProjectView.js, src/components/projects/project/__tests__/ProjectView.test.js, src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap, src/containers/dashboard/__tests__/DashboardViewStateContainer.test.js, src/containers/projects/__tests__/ListProjectsViewStateContainer.test.js, src/containers/projects/__tests__/ProjectViewStateContainer.test.js
This commit will add new unit tests for the rendering of the pages. It
will also add unit tests for the view state containers which will mock
responses from the HTTP server.
Bug: https://github.com/eclipse/sirius-components/issues/21
=> Contribute additional tests

docs/designsystem.adoc, src/app.css, src/components/aside/Aside.js, src/components/aside/__tests__/__snapshots__/Aside.test.js.snap, src/components/cards/Card.css, src/components/cards/Card.js, src/components/dashboard/DashboardView.css, src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap, src/components/form/Form.css, src/components/icons/IconRun.css, src/components/icons/IconRun.js, src/components/list/List.css, src/components/list/List.js, src/components/list/README.adoc, src/components/projects/ProjectRepresentationsListCard.js, src/components/projects/ProjectSemanticResourcesListCard.js, src/components/projects/ProjectSummaryCard.js, src/components/projects/ProjectsListCard.css, src/components/projects/ProjectsListCard.js, src/components/projects/listprojects/__tests__/__snapshots__/ListProjectsView.test.js.snap, src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap, src/components/tabbar/TabBar.js, src/components/tabbar/__tests__/__snapshots__/TabBar.test.js.snap, src/components/workflow/WorkflowCard.js, src/components/workflow/__tests__/__snapshots__/WorkflowCard.test.js.snap
This commit updates the layout of the list components. The "smart" List
Item component has been removed in order to use more explicit components
which are easier to manipulate and understand.
The FooterLink component has also been removed in prevision of the
refactoring of the card components. Some changes in the fonts and sizes
have occurred.
Bug: https://github.com/eclipse/sirius-components/issues/36
=> Improve the list components' layout

.vscode/settings.json
Bug: https://github.com/eclipse/sirius-components/issues/46
Signed-off-by: Guillaume Coutable <guillaume.coutable@obeo.fr>
=> Update settings.json to remove organize imports

src/components/projects/ProjectHeaderCard.js
Bug: https://github.com/eclipse/sirius-components/issues/64
=> Switch to default props in EditDescription

src/components/buttons/Button.js, src/components/buttons/ButtonConstants.js, src/components/buttons/__tests__/Button.test.js, src/components/projects/NewProjectCard.js
Bug: https://github.com/eclipse/sirius-components/issues/66
=> Extract the button constants from the button component

src/app.css, src/components/app/App.css, src/components/buttons/Button.css, src/components/buttons/Button.js, src/components/buttons/__tests__/__snapshots__/Button.test.js.snap, src/components/cards/Card.css, src/components/cards/Card.js, src/components/cards/__tests__/Card.test.js, src/components/cards/__tests__/__snapshots__/Card.test.js.snap, src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap, src/components/list/List.js, src/components/navbar/Navbar.js, src/components/navbar/__tests__/__snapshots__/Navbar.test.js.snap, src/components/projects/NewProjectCard.js, src/components/projects/ProjectHeaderCard.js, src/components/projects/ProjectRepresentationsListCard.js, src/components/projects/ProjectSemanticResourcesListCard.js, src/components/projects/ProjectSummaryCard.js, src/components/projects/ProjectsListCard.js, src/components/projects/listprojects/__tests__/__snapshots__/ListProjectsView.test.js.snap, src/components/projects/newproject/__tests__/__snapshots__/NewProjectView.test.js.snap, src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap, src/components/tabbar/TabBar.js, src/components/tabbar/__tests__/__snapshots__/TabBar.test.js.snap, src/components/text/Text.css, src/components/text/Text.js, src/components/text/TextConstants.js, src/components/workflow/WorkflowCard.js, src/components/workflow/__tests__/__snapshots__/WorkflowCard.test.js.snap
A new text component has been introduced in order to handle styling.
This component will replace the global CSS classes used before. It will
be easier to reuse instead of trying to create all the possible outcome
for our given text styles and layout needs.
As a result, some components like PrimaryTitle or SecondaryTitle have
been removed.
Bug: https://github.com/eclipse/sirius-components/issues/62
=> Use a component-based approach for text management

src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap, src/components/tabbar/TabBar.js, src/components/tabbar/__tests__/__snapshots__/TabBar.test.js.snap, src/components/workflow/__tests__/__snapshots__/WorkflowCard.test.js.snap
Bug: https://github.com/eclipse/sirius-components/issues/76
=> Fix an issue with long labels in the tab bar

.vscode/settings.json
Bug: https://github.com/eclipse/sirius-components/issues/78
=> Remove the prettier formatting on paste

src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap, src/components/loading/Loading.css, src/components/loading/Loading.js, src/components/projects/listprojects/__tests__/__snapshots__/ListProjectsView.test.js.snap, src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap, src/components/text/Text.css, src/components/text/Text.js
The Loading component has been improved and loading support has been
added to the Text component too. Those components can now be reused to
improve the loading support of our pages.
Bug: https://github.com/eclipse/sirius-components/issues/60
=> Improve support for loading

src/common/dispatcherCreator.js, src/components/app/App.js, src/components/app/ie11.css
1/ Remove a call to Array#includes
2/ Remove the use of URLSearchParams
3/ Add some CSS to support IE11
Bug: https://github.com/eclipse/sirius-components/issues/91
=> Fix some compatibility issues with IE11

package.json, yarn.lock
Bug: https://github.com/eclipse/sirius-components/issues/95
=> Move to React 16.4.1

src/components/aside/Aside.css, src/components/aside/Aside.js, src/components/aside/MainLink.css, src/components/aside/MainLink.js, src/components/aside/__tests__/__snapshots__/Aside.test.js.snap, src/components/dashboard/DashboardOverviewSection.css, src/components/dashboard/DashboardOverviewSection.js, src/components/dashboard/DashboardProjectsSection.css, src/components/dashboard/DashboardProjectsSection.js, src/components/dashboard/DashboardView.js, src/components/dashboard/__tests__/DashboardView.test.js, src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap, src/components/text/Text.js
The Dashboard has been separated in multiple components for a better
maintainability.
Bug: https://github.com/eclipse/sirius-components/issues/50
=> Improve the organization of the dashboard

package.json, src/components/aside/__tests__/__snapshots__/Aside.test.js.snap, src/components/blank/__tests__/__snapshots__/BlankCard.test.js.snap, src/components/buttons/__tests__/__snapshots__/Button.test.js.snap, src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap, src/components/error/__tests__/__snapshots__/ErrorCard.test.js.snap, src/components/info/__tests__/__snapshots__/InfoCard.test.js.snap, src/components/navbar/__tests__/__snapshots__/Navbar.test.js.snap, src/components/projects/listprojects/__tests__/__snapshots__/ListProjectsView.test.js.snap, src/components/projects/newproject/__tests__/__snapshots__/NewProjectView.test.js.snap, src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap, src/components/spacing/Spacing.js, src/components/workflow/__tests__/__snapshots__/WorkflowCard.test.js.snap, src/setupProxy.js, yarn.lock
=> Update the dependencies

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingConverter.java
=> [105] Take Domain class into account for DomainBasedEdges conversion

backend/sirius-web-spring-tests/pom.xml, backend/sirius-web-tests/pom.xml
Bug: https://github.com/eclipse-sirius/sirius-components/issues/147
=> [147] Upgrade to ArchUnit 0.14.1

backend/sirius-web-spring-graphql/src/main/java/org/eclipse/sirius/web/spring/graphql/controllers/GraphQLPayload.java, backend/sirius-web-spring-graphql/src/main/java/org/eclipse/sirius/web/spring/graphql/ws/GraphQLWebSocketHandler.java, doc/adrs/000_adopt_adrs.adoc, doc/adrs/001_switch_to_apollo_client.adoc, frontend/package-lock.json, frontend/package.json, frontend/src/common/GraphQLHooks.ts, frontend/src/diagram/DiagramWebSocketContainer.tsx, frontend/src/diagram/__tests__/reducer.test.ts, frontend/src/diagram/operations.ts, frontend/src/diagram/reducer.ts
This is not completely finished, in particular I have not tested the error handling. In particular the `connection_error` message type which was handled before is ignored at the moment. I'm publishing it anyway to get feedback on the rest while I continue on the error handling.
=> Use Apollo instead of our custom GraphQL hooks for the diagram part

.github/ISSUE_TEMPLATE/feature_template.md
Add the missing yaml header in issue_template.md
=> [cleanup] Add the missing yaml header

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ContainerMappingConverter.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingConverter.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/LabelStyleDescriptionConverter.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeMappingConverter.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/165
...
We are sometimes using EMF while it's not useful
...
...
=> [165] Remove some useless dependencies to EMF

.github/workflows/build.yml
Bug: https://github.com/eclipse-sirius/sirius-components/issues/174
...
...
...
...
=> [174] Prevent double build for pull requests

backend/sirius-web-interpreter/src/main/java/org/eclipse/sirius/web/interpreter/ExpressionConverter.java, backend/sirius-web-interpreter/src/test/java/org/eclipse/sirius/web/interpreter/AQLInterpreterTestCases.java, backend/sirius-web-interpreter/src/test/java/org/eclipse/sirius/web/interpreter/ExpressionConverterTestCases.java
=> [104] Fix NPE on null AQL expression

frontend/package-lock.json, frontend/package.json
Bug: https://github.com/eclipse-sirius/sirius-components/issues/173
...
...
...
...
=> [173] Add a dependency to @material-ui/icons

sample/test-sample/frontend/package-lock.json, sample/test-sample/frontend/package.json
=> [173] Add sample project dependencies to MaterialUI and XState

sample/test-sample/frontend/package-lock.json, sample/test-sample/frontend/package.json
Signed-off-by: Florian Barbin <florian.barbin@obeo.fr>
Issue 173
...
...
...
...
=> [173] Add missing dependencies to the test sample

.github/workflows/build.yml
=> [cleanup] Do not trigger the build for a documentation change

backend/sirius-web-collaborative-diagrams-api/src/main/java/org/eclipse/sirius/web/collaborative/diagrams/api/IDiagramContext.java, backend/sirius-web-collaborative-diagrams-api/src/main/java/org/eclipse/sirius/web/collaborative/diagrams/api/IDiagramCreationService.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/ViewCreationRequest.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/DiagramComponent.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/DiagramComponentProps.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeComponent.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeComponentProps.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTestCases.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererNodeTestCases.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/UnsynchronizedDiagramTestCases.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramContext.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramCreationService.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramEventProcessor.java, backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/NoOpDiagramCreationService.java, doc/adrs/005_add_support_for_view_creation_request.adoc
=> [127] Add View creation request

backend/sirius-web-spring/src/main/java/org/eclipse/sirius/web/spring/controllers/ImagesController.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/195
=> [195] Fix an issue with image extensions

frontend/src/form/FormWebSocketContainer.tsx, frontend/src/form/reducer.ts
https://github.com/eclipse-sirius/sirius-components/issues/170
Use Apollo for the Form representation subscriptions.
The change should have no visible impact. The existing test suites should be enough.
=> [170] Move Form to Apollo

doc/adrs/006_migrate_our_statemachines_to_xstate.adoc, doc/adrs/007_adopt_stable_identifiers_for_diagrams.adoc, doc/adrs/008_add_support_for_incremental_layout.adoc
...
Document the realization of https://github.com/Obeo/ocp/issues/31
...
...
=> [doc] Contribute an ADR on incremental layout

frontend/src/diagram/sprotty/WebSocketDiagramServer.tsx
Bug: https://github.com/eclipse-sirius/sirius-components/issues/217
This fixes very subtle bugs that appear from time to time and where quite complex to detect.
...
...
...
=> [217] Fix invalid use of async / await in WebSocketDiagramServer

backend/sirius-web-collaborative-api/src/main/java/org/eclipse/sirius/web/collaborative/api/dto/DeleteRepresentationInput.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/227
...
...
...
...
=> [227] Fix a typo in DeleteRepresentationInput

frontend/.vscode/snippets.code-snippets
See https://github.com/Microsoft/vscode/issues/62521#issuecomment-436087831
=> [fix] Fix VS Code snippet configuration

.github/workflows/build.yml
=> [releng] Improve the detection of new tags for the deployment

.github/workflows/build.yml
=> [releng] Fix the pattern used to match branches

frontend/src/diagram/DiagramWebSocketContainer.tsx, frontend/src/diagram/DiagramWebSocketContainer.types.ts, frontend/src/views/edit-project/EditProjectView.types.ts
Bug: https://github.com/eclipse-sirius/sirius-components/issues/252
=> [252] Improve the typing of the DiagramWebSocketContainer

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/ObjectService.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/AllSiriusWebEMFTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/ObjectServiceTestCases.java
=> [256] Fix support for EMF composed images

.dependabot/config.yml
=> [releng] Add dependabot configuration to minimize false positives

backend/sirius-web-core-api/pom.xml
=> [releng] Fix an invalid version in Sirius Web Core API

frontend/src/diagram/DiagramWebSocketContainer.tsx, frontend/src/diagram/__tests__/reducer.test.ts, frontend/src/diagram/reducer.ts, frontend/src/diagram/sprotty/DependencyInjection.ts, frontend/src/diagram/sprotty/__tests__/convertDiagram.test.ts, frontend/src/diagram/sprotty/convertDiagram.tsx, frontend/src/diagram/sprotty/views/DiagramView.tsx, frontend/src/diagram/sprotty/views/ImageView.tsx, frontend/src/diagram/sprotty/views/RectangleView.tsx, frontend/src/index.ts
#131
- make an edge flow between two processor => cursor should be copy
- make an edge flow between from a processor to a Fan (or the diagram background) => cursor should be 'not-allowed'
=> [131] Add tool apply feedback

frontend/src/views/new-project/NewProjectView.tsx
=> [cleanup] Remove useless code in the NewProjectView

frontend/package-lock.json, frontend/package.json, frontend/src/core/contextmenu/ContextMenu.tsx
Bug: https://github.com/eclipse-sirius/sirius-components/issues/152
=> [152] Update some of our dependencies

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeMappingConverter.java
Use a default style for the label in this case.
=> [fix] Fix NPE on missing NodeMapping.getStyle()

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ContainerMappingConverter.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ContainerMappingStyleProvider.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ContainerStyleDescriptionProvider.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingConverter.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingStyleProvider.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeStyleDescriptionProvider.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/LabelStyleDescriptionConverter.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeMappingConverter.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeMappingStyleProvider.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeStyleDescriptionProvider.java, backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/AllSiriusWebCompatibilityTests.java, backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/diagrams/BasicLabelStyleDescriptionPopulator.java, backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/diagrams/MappingConverterTestCases.java, backend/sirius-web-diagrams-tests/src/main/java/org/eclipse/sirius/web/diagrams/tests/TestDiagramDescriptionBuilder.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/LabelComponent.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/description/LabelDescription.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTestCases.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererNodeTestCases.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/UnsynchronizedDiagramTestCases.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/diagrams/EdgeMappingConverterTestCases.java
The conditional style properties of Containers and Nodes mappings were not all taking into account.
This PR fixes the conditional style properties of Containers and Nodes mappings that were not all taking into account.
This PR does not fix the conditional style properties of EdgeMappings.
=> Fix conditional style handling for containers and nodes

doc/adrs/012_refactor_incremental_layout.adoc
#233 
...
This PR contributes a new ADR describing choices made to refactor the incremental layout.
...
...
...
=> Refactor the layout algorithm

doc/adrs/015_add_resize_support_in_diagram.adoc
=> Add an ADR for the resizing support

backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutedDiagramProvider.java, backend/sirius-web-diagrams-layout/src/test/java/org/eclipse/sirius/web/diagrams/layout/services/DiagramConverterTestCases.java, backend/sirius-web-diagrams-layout/src/test/java/org/eclipse/sirius/web/diagrams/layout/services/ImageNodeStyleSizeProviderTestCases.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/ImageNodeStyleSizeProvider.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/ImageSizeProvider.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/Position.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/Size.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/TextBoundsProvider.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/DiagramComponent.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/EdgeLabelPositionProvider.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/EdgeRoutingPointsProvider.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeComponent.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeLabelPositionProvider.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodePositionProvider.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeSizeProvider.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/components/EdgeLabelPositionProviderTestCases.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/components/EdgeRoutingPointsProviderTestCases.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/components/NodeLabelPositionProviderTestCases.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/components/NodePositionProviderTestCases.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/UpdateNodePositionEventHandler.java, backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/RenameDiagramEventHandlerTestCases.java
=> Add new builders for position and size

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ToolConverter.java
=> [408] Add missing 'element' variable for delete tool

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/forms/GroupDescriptionConverter.java
=> [fix] Fix NPE in forms on missing Group label expression

backend/sirius-web-tests/src/test/java/org/eclipse/sirius/web/tests/GeneralPurposeTestCases.java
Signed-off-by: Guillaume Coutable <guillaume.coutable@obeo.fr>
Make the build work locally on Windows
=> [test] Fix path used to ignore generated files for windows users

backend/sirius-web-diagrams-layout/pom.xml, backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutService.java
This commit can help to understand what layout ELK has produced.
The result can be pasted in
https://rtsys.informatik.uni-kiel.de/elklive/json.html to see the
produced layout.
=> [446] Print in the console the elk graph in json

doc/adrs/007_adopt_stable_identifiers_for_diagrams.adoc
Mention additional consequences of the ADR that we should keep in mind.
=> [doc] Complete ADR-007

doc/adrs/018_adopt_a_subset_of_ecore_to_define_data_schemas.adoc
This is just a first draft to initiate the discussion.
=> Add ADR describing the domain DSL (simplified Ecore)

doc/adrs/019_support_simple_diagram_definitions.adoc
This first draft does not support `DynamicFor` and `DynamicIf` elements.
=> [243] Add ADR for simple diagram definitions

frontend/src/common/BrandingContext.tsx, frontend/src/navbar/NavigationBar.tsx
https://github.com/eclipse-sirius/sirius-web/issues/59
It prevents some links to be displayed with the wrong color.
=> [59] Fix visited link color

frontend/src/diagram/Toolbar.tsx, frontend/src/index.ts, frontend/src/properties/Properties.tsx, frontend/src/properties/propertysections/PropertySectionLabel.tsx
https://github.com/eclipse-sirius/sirius-web/issues/58
It improves theming possibilities.
=> [58] Remove the hardcoded background color from avatars

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/diagrams/DiagramDescriptionConverter.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/description/DiagramDescription.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramCreationService.java
https://github.com/eclipse-sirius/sirius-components/issues/503
At creation time, the layout mode of a diagram is determined by its
diagram description.
=> [503] Choose the layout mode of a representation

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/DocumentService.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/ProjectExportService.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/UploadDocumentEventHandler.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/431
- Support the download and upload of a document that is an instance of a dynamically defined domain.
- Support the download and upload of a project containing such document
1. Creates a project
2. Adds a Domain-based document
3. In a second project, creates a dynamic document based on the Domain
4. Download the second project or the dynamic document.
=> [431] Fix project and document upload/download that contain instance of a dynamically-defined domain

backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutConfiguratorRegistry.java, backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/updater/ContainmentUpdater.java
It fixes the node label padding for the incremental layout to be the same as the automatic layout (ELK).
=> [fix] Fix label padding for nodes

backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/SiriusWebLayoutConfigurator.java
Bug: #537
Signed-off-by: j-barata <jean.barata@thalesgroup.com>
#537 
fixes the issue
=> [537] Layout configurator override issue

frontend/src/onboarding/NewRepresentationArea.tsx, frontend/src/properties/PropertiesWebSocketContainer.tsx, frontend/src/properties/PropertiesWebSocketContainerMachine.ts, frontend/src/tree/TreeItem.tsx, frontend/src/workbench/RepresentationContext.ts, frontend/src/workbench/RepresentationContext.types.ts, frontend/src/workbench/Workbench.tsx, frontend/src/workbench/WorkbenchMachine.ts
It eases the contribution of new kinds of representation in the front-end
=> [enh] Add the initial support of contributed representations

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditingContextEPackageService.java
=> [fix] Include global EPackages in the result of IEditingContextEPackageService

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditingContextEPackageService.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/DynamicRepresentationDescriptionService.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
=> [enh] Only enable Domain and View conversion if the proper feature flag is set

backend/sirius-web-diagrams-tests/src/main/java/org/eclipse/sirius/web/diagrams/tests/TestDiagramBuilder.java
This issue is partially responsible of some previous test failures
=> [test] Update the default vaue of the TestDiagramBuilder

frontend/package.json, frontend/src/index.ts, frontend/src/onboarding/NewDocumentArea.types.ts, frontend/src/onboarding/NewRepresentationArea.types.ts, frontend/src/onboarding/RepresentationsArea.types.ts
Bug: https://github.com/eclipse-sirius/sirius-components/issues/607
=> [607] Format the TypeScript code with Prettier

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextEPackageService.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/DynamicRepresentationDescriptionService.java
=> [cleanup] Simplify studio definition feature flag implementation

backend/sirius-web-api/pom.xml, backend/sirius-web-collaborative-api/pom.xml, backend/sirius-web-collaborative-diagrams-api/pom.xml, backend/sirius-web-collaborative-forms-api/pom.xml, backend/sirius-web-collaborative-trees-api/pom.xml, backend/sirius-web-compatibility/pom.xml, backend/sirius-web-components/pom.xml, backend/sirius-web-core-api/pom.xml, backend/sirius-web-diagrams-layout/pom.xml, backend/sirius-web-diagrams/pom.xml, backend/sirius-web-emf/pom.xml, backend/sirius-web-forms/pom.xml, backend/sirius-web-graphql-schema/pom.xml, backend/sirius-web-graphql-utils/pom.xml, backend/sirius-web-graphql/pom.xml, backend/sirius-web-interpreter/pom.xml, backend/sirius-web-persistence/pom.xml, backend/sirius-web-services-api/pom.xml, backend/sirius-web-services/pom.xml, backend/sirius-web-spring-collaborative-diagrams/pom.xml, backend/sirius-web-spring-collaborative-forms/pom.xml, backend/sirius-web-spring-collaborative-trees/pom.xml, backend/sirius-web-spring-collaborative/pom.xml, backend/sirius-web-spring-graphql/pom.xml, backend/sirius-web-spring-tests/pom.xml, backend/sirius-web-spring/pom.xml, backend/sirius-web-tests/pom.xml, backend/sirius-web-trees/pom.xml
It adds a dependency to `spring-boot-starter-test` in all projects that have tests to execute. With this dependency, all tests should be executed at build time.
=> [test] Make all tests run

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EMFValidationService.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/629
The current behavior shows the string value of the object involved in
the validation error. The improved version shows the real label of the
involved object.
Current:
Improved:
No side effects
=> [629] Improve validation messages

backend/sirius-web-emf/pom.xml
=> [releng] Switch to EMFJson 2.3.1-SNAPSHOT

backend/sirius-web-spring-graphql/src/main/java/org/eclipse/sirius/web/spring/graphql/configuration/WebSocketConfiguration.java
=> [fix] Enable support for configuring multiple origins for WS

backend/sirius-web-collaborative-selection-api/src/main/java/org/eclipse/sirius/web/collaborative/selection/api/SelectionConfiguration.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/SelectModelElementVariableConverter.java, backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionSelectionEventDataFetcher.java, backend/sirius-web-selection/src/main/java/org/eclipse/sirius/web/selection/Selection.java, backend/sirius-web-selection/src/main/java/org/eclipse/sirius/web/selection/description/SelectionDescription.java, backend/sirius-web-selection/src/main/java/org/eclipse/sirius/web/selection/renderer/SelectionRenderer.java, backend/sirius-web-spring-collaborative-selection/src/main/java/org/eclipse/sirius/web/spring/collaborative/selection/SelectionEventProcessor.java, backend/sirius-web-spring-collaborative-selection/src/main/java/org/eclipse/sirius/web/spring/collaborative/selection/SelectionEventProcessorFactory.java, frontend/src/diagram/DiagramWebSocketContainerMachine.ts, frontend/src/selection/SelectionDialogWebSocketContainer.tsx, frontend/src/selection/SelectionDialogWebSocketContainerMachine.ts
Bug: https://github.com/eclipse-sirius/sirius-components/issues/559
Fix SelectionDialog collaborative edition & lifecycle issues :
- Fix deletion of the representation while SelectionDialog is opened
- Fix deletion of the object on which SelectionDialog is opened
- Fix SelectionDialog content while opened in different projects
=> [559] Fix SelectionDialog collaborative edition & lifecycle issues

backend/sirius-web-collaborative-validation-api/src/main/java/org/eclipse/sirius/web/collaborative/validation/api/IValidationService.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/forms/WidgetDescriptionConverter.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/EBooleanIfDescriptionProvider.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/EEnumIfDescriptionProvider.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/EStringIfDescriptionProvider.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/MonoValuedNonContainmentReferenceIfDescriptionProvider.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/MultiValuedNonContainmentReferenceIfDescriptionProvider.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/NumberIfDescriptionProvider.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/PropertiesDefaultDescriptionProvider.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/PropertiesValidationProvider.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/api/IPropertiesValidationProvider.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/properties/EStringIfDescriptionProviderTests.java, frontend/src/validation/ValidationWebSocketContainer.tsx
https://github.com/eclipse-sirius/sirius-components/issues/655
=> [655] Add the support for validation in default details view

backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ConditionalEdgeStyleImpl.java, backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/EdgeStyleImpl.java, backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java, backend/sirius-web-view/src/main/resources/model/view.ecore
=> [fix] Fix default edge decorator on View definitions

backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/DomainFactoryImpl.java, backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/DomainPackageImpl.java, backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/FeatureImpl.java, backend/sirius-web-domain/src/main/resources/model/domain.ecore
https://github.com/eclipse-sirius/sirius-components/issues/654
=> [654] Set Feature#optional feature default value to `true`

doc/adrs/024_add_support_for_view_deletion_requests.adoc, doc/adrs/025_switch_to_a_schema_first_approach_for_our_graphql_schema.adoc, doc/adrs/026_improve_the_performance_of_unsynchronized_nodes.adoc, doc/adrs/027_make_the_explorer_independent_from_modeling_concepts.adoc, doc/adrs/028_move_representations_out_of_the_explorer.adoc, doc/adrs/029_introduce_some_object_services.adoc
=> [doc] Add various ADRs to the 0.5.0 release of Sirius Components

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/CustomImage.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ICustomImageSearchService.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/StylesFactory.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewPropertiesConfigurer.java, backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/entities/CustomImageEntity.java, backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/repositories/ICustomImageRepository.java, backend/sirius-web-persistence/src/main/resources/db/changelog/sirius-web-schema.sql, backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/images/ICustomImageContentService.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/images/CustomImageContentService.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/images/CustomImageSearchService.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/DynamicRepresentationDescriptionService.java, backend/sirius-web-spring/src/main/java/org/eclipse/sirius/web/spring/controllers/ImagesController.java, backend/sirius-web-spring/src/test/java/org/eclipse/sirius/web/spring/controllers/ImagesControllerTests.java
- [563] Replace CustomImage.fileName with contentType
- [563] Do not use a random id for custom images
- [563] Split the single ICustomImagesServices in two
- [563] Add editingContextId to ICustomImages{Search,Content}Service
- [563] Move ICustomImagesContentService into sirius-web-services
=> Improve support for custom images

doc/adrs/030_add_a_link_representation.adoc
=> [doc] Add an ADR on the link representation

backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/DiagramTypesProvider.java, backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/diagram/DiagramAutoLayoutDataFetcher.java, frontend/src/diagram/DiagramWebSocketContainer.tsx, frontend/src/diagram/Toolbar.tsx, frontend/src/diagram/Toolbar.types.ts, frontend/src/diagram/operations.ts, frontend/src/diagram/sprotty/__tests__/convertDiagram.test.ts, frontend/src/diagram/sprotty/convertDiagram.tsx
- [514] Disable move/resize of nodes on auto-layout diagrams
- [514] Disable the arrange all button for auto-layouted diagrams
=> Disable move/resize of nodes on auto-layout diagrams

backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessor.java
=> [fix] Avoid publishing rename event if there are no subscribers

backend/sirius-web-domain-design/pom.xml, backend/sirius-web-domain-edit/pom.xml, backend/sirius-web-domain/pom.xml, backend/sirius-web-emf/pom.xml, backend/sirius-web-tests/src/test/java/org/eclipse/sirius/web/tests/GeneralPurposeTests.java, backend/sirius-web-view-edit/pom.xml, backend/sirius-web-view/pom.xml
=> [fix] Removes flow from where it is not needed

doc/adrs/031_separate_metadata_from_representations.adoc, doc/adrs/032_relax_our_constraints_on_some_of_our_identifiers.adoc
=> [doc] Contribute additional ADRs on metadata and identifiers

frontend/src/modals/new-representation/NewRepresentationModal.tsx
=> [test] Add additional data-testid

backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/Node.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java, doc/adrs/033_add_support_for_ unsynchronized_tools.adoc
Bug: https://github.com/eclipse-sirius/sirius-components/issues/690
Signed-off-by: Hugo Marchadour <hugo.marchadour@obeo.fr>
...
...
...
...
=> [690] Add selectedNode variable to execute tools

.github/workflows/build.yml
=> [releng] Trigger a pull request build only for remote PRs

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/DomainClassPredicate.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/SemanticCandidatesProvider.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/diagrams/CanCreateDiagramPredicate.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainValidator.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewValidator.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/DomainClassPredicateTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/validation/DiagnosticAssert.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/validation/DomainValidatorTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/validation/ViewValidatorTests.java, frontend/src/onboarding/NewRepresentationArea.tsx
- [fix] Make the onboard area more robust when no selection is set
- [738] Fix View validation when using qualified domain type names
- [761] Validate names of domains, entities and their features
...
...
...
...
=> Improve Domain validation

CHANGELOG.adoc
The CHANGELOG will be used to communicate with consumers of the Sirius
Components project. It will be maintained by hand by the contributors
since our Git history does not have the level of details required and
it is more oriented toward communication with other developers of the
project. Those developers are quite familiar with the evolution of the
project contrary to external consumers.
=> [releng] Contribute the first version of the CHANGELOG

CHANGELOG.adoc, backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessorRegistry.java, backend/sirius-web-spring-graphql/src/main/java/org/eclipse/sirius/web/spring/graphql/configuration/WebSocketConfiguration.java, backend/sirius-web-spring-starter/pom.xml, backend/sirius-web-spring-starter/src/main/java/org/eclipse/sirius/web/starter/configurationproperties/CorsConfigurationProperty.java, backend/sirius-web-spring-starter/src/main/java/org/eclipse/sirius/web/starter/configurationproperties/EditingContextConfigurationProperty.java, backend/sirius-web-spring-starter/src/main/java/org/eclipse/sirius/web/starter/configurationproperties/SiriusComponentsConfigurationProperties.java, doc/configuration.adoc
See the CHANGELOG for additional details
Bug: https://github.com/eclipse-sirius/sirius-components/issues/804
=> [804] List and update the various configuration properties

CHANGELOG.adoc, frontend/src/diagram/Toolbar.tsx
https://user-images.githubusercontent.com/10608/138753299-c9fc9c85-b898-4155-bfbb-5885493649d8.mp4
=> [799] Add tooltips to the diagram toolbar's icons

CHANGELOG.adoc, doc/adrs/036_adopt_a_more_structured_selection.adoc
https://github.com/eclipse-sirius/sirius-components/issues/818
=> [818] Contribute the ADR about a more structured selection

.gitignore, CHANGELOG.adoc, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/api/IExternalJavaActionProvider.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/modeloperations/ChildModelOperationHandler.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/modeloperations/ExternalJavaActionOperationHandler.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/modeloperations/ModelOperationHandlerSwitch.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/configuration/CompatibilityConfiguration.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/diagrams/EdgeMappingConverterTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/ChangeContextOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/CreateInstanceOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/CreateViewOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/DeleteViewOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/ForOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/IfOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/LetOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/MoveElementOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/RemoveElementOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/SetValueOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/SwitchOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/UnsetOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/properties/FormRendererTests.java
The external java operation is useful for developers to implement complex business
Add external java action support
...
...
=> Add support for external java actions

CHANGELOG.adoc
=> [doc] Update the CHANGELOG for the upcoming release

CHANGELOG.adoc, doc/adrs/036_adopt_a_more_structured_selection.adoc, frontend/src/diagram/DiagramWebSocketContainer.tsx, frontend/src/diagram/DiagramWebSocketContainerMachine.ts, frontend/src/diagram/sprotty/DiagramServer.tsx, frontend/src/explorer/Explorer.types.ts, frontend/src/explorer/ExplorerWebSocketContainer.types.ts, frontend/src/modals/new-object/NewObjectModal.tsx, frontend/src/modals/new-object/NewObjectModalMachine.ts, frontend/src/modals/new-representation/NewRepresentationModal.tsx, frontend/src/modals/new-root-object/NewRootObjectModal.tsx, frontend/src/modals/new-root-object/NewRootObjectModalMachine.ts, frontend/src/onboarding/NewRepresentationArea.tsx, frontend/src/onboarding/NewRepresentationArea.types.ts, frontend/src/onboarding/OnboardArea.tsx, frontend/src/onboarding/OnboardArea.types.ts, frontend/src/onboarding/RepresentationsArea.tsx, frontend/src/properties/PropertiesWebSocketContainer.tsx, frontend/src/properties/PropertiesWebSocketContainerMachine.ts, frontend/src/properties/propertysections/ListPropertySection.tsx, frontend/src/representations/RepresentationsWebSocketContainer.tsx, frontend/src/representations/RepresentationsWebSocketContainerMachine.ts, frontend/src/tree/Tree.types.ts, frontend/src/tree/TreeItem.tsx, frontend/src/tree/TreeItem.types.ts, frontend/src/workbench/LeftSite.types.ts, frontend/src/workbench/RepresentationNavigation.tsx, frontend/src/workbench/Workbench.tsx, frontend/src/workbench/Workbench.types.ts, frontend/src/workbench/WorkbenchMachine.ts
https://github.com/eclipse-sirius/sirius-components/issues/134
This commit does not change the behavior of the workbench, it only prepares
it and most workbench components to a new selection API to support multiple
selections.
=> [134] Switch to a multi-selection API in the workbench

CHANGELOG.adoc, backend/sirius-web-spring-starter/pom.xml, backend/sirius-web-spring-starter/src/main/java/org/eclipse/sirius/web/starter/configuration/ObjectMapperConfiguration.java
- The object mapper can serialize/deserialize date into/from json
- Contribute to the object mapper created by spring instead of creating
one ourselves
=> [enh] Improve object mapper configuration

backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/ELKDiagramConverter.java
I'm not sure yet how this is related to #832.
=> [fix] Fix border node size computation

frontend/src/index.ts
Signed-off-by: Yvan Lussaud <yvan.lussaud@obeo.fr>
#893
export tree/TreeItemContextMenu
...
...
=> [893] Export tree/TreeItemContextMenu

backend/sirius-web-domain-edit/src/main/java/org/eclipse/sirius/web/domain/provider/DomainItemProviderAdapterFactory.java, backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/DomainFactory.java, backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/Feature.java, backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/NamedElement.java, backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/DomainFactoryImpl.java, backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/DomainPackageImpl.java, backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/FeatureImpl.java, backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/NamedElementImpl.java, backend/sirius-web-domain/src/main/resources/model/domain.ecore, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/ObjectService.java
Theire definition in the Ecore was broken, which triggered a bug when looking up for EMF Edit icons which are missing (also handled in the PR).
=> Make the NamedElement and Feature types abstract

backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/representations/SubscriptionManager.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/746
...
...
...
...
=> [746] Fix SubscriptionManager.isEmpty()

CHANGELOG.adoc, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ToolConverter.java, backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/diagrams/DiagramDescriptionNodeAndEdgeDescriptionsPopulator.java, backend/sirius-web-diagrams-tests/src/main/java/org/eclipse/sirius/web/diagrams/tests/TestDiagramDescriptionBuilder.java, backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/description/DiagramDescription.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTests.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererNodeTests.java, backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/UnsynchronizedDiagramTests.java, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/CreateViewOperationHandlerTests.java, backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/DeleteViewOperationHandlerTests.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/dto/DropOnDiagramInput.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/dto/DropOnDiagramSuccessPayload.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DropOnDiagramEventHandler.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/messages/CollaborativeDiagramMessageService.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/messages/ICollaborativeDiagramMessageService.java, backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/messages/MessageConstants.java, backend/sirius-web-spring-collaborative-diagrams/src/main/resources/messages/sirius-web-spring-collaborative-diagrams.properties, backend/sirius-web-spring-collaborative-diagrams/src/main/resources/schema/diagram.graphqls, backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/CreateDiagramEventHandlerTests.java, backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/NoOpCollaborativeDiagramMessageService.java, doc/adrs/034_add_support_for_drag_and_drop.adoc, frontend/src/common/dataTransferTypes.ts, frontend/src/diagram/DiagramWebSocketContainer.tsx, frontend/src/diagram/DropArea.module.css, frontend/src/diagram/DropArea.tsx, frontend/src/diagram/DropArea.types.ts, frontend/src/diagram/DropAreaMachine.ts, frontend/src/index.ts, frontend/src/tree/TreeItem.tsx
=> [132] Add a drop tool

CHANGELOG.adoc, backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/ISiriusWebLayoutConfigurator.java, backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutConfiguratorRegistry.java, backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutService.java, backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/SiriusWebLayoutConfigurator.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/896
Allow to make specific changes before and after the layout
=> [896] Allow to make specific changes before and after the layout

backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/components/WidgetIdCounter.java, backend/sirius-web-resources/checkstyle/CheckstyleConfiguration.xml
=> [enh] Update the Checkstyle configuration to prevent package modifiers

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
Put edge tools in the proper dedicated section.
...
...
...
...
=> [fix] Fix bug in edge tools conversion

backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/EdgeDescriptionItemProvider.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/888
...
...
...
...
=> [888] Fix the initial expression in default edge create tools

frontend/src/diagram/DropArea.tsx, frontend/src/tree/TreeItem.tsx
Bug: https://github.com/eclipse-sirius/sirius-components/issues/132
=> [132] Fix a regression with the drop tool

CHANGELOG.adoc, frontend/src/diagram/DiagramWebSocketContainer.tsx, frontend/src/diagram/DiagramWebSocketContainerMachine.ts, frontend/src/diagram/sprotty/DependencyInjection.ts, frontend/src/diagram/sprotty/Diagram.types.ts, frontend/src/diagram/sprotty/DiagramServer.tsx, frontend/src/diagram/sprotty/DiagramServer.types.ts, frontend/src/diagram/sprotty/__tests__/convertDiagram.test.ts, frontend/src/diagram/sprotty/convertDiagram.tsx
- [914] Extract the DiagramMouseListener and improve its typing
- [914] Add the graphical selection for nodes and edges
=> [914] Add the graphical selection for nodes and edges

CHANGELOG.adoc, backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java, backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/RepresentationDescriptionItemProvider.java, backend/sirius-web-view-edit/src/main/resources/plugin.properties, backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/RepresentationDescription.java, backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java, backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/RepresentationDescriptionImpl.java, backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java, backend/sirius-web-view/src/main/resources/model/view.ecore, backend/sirius-web-view/src/main/resources/model/view.genmodel
See https://github.com/eclipse-sirius/sirius-components/issues/936
=> [936] Add support for preconditionExpression in dynamic representations

CHANGELOG.adoc
=> [doc] Mention external contributors to v2022.01.0 in the CHANGELOG

frontend/src/diagram/DiagramWebSocketContainer.types.ts, frontend/src/diagram/palette/ContextualPalette.tsx
Bug: https://github.com/eclipse-sirius/sirius-components/issues/822
=> [822] Fix a crash while clicking on an edge

backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/editingcontext/EditingContextEventProcessor.java, backend/sirius-web-tests/src/test/java/org/eclipse/sirius/web/tests/GeneralPurposeTests.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/972
=> [972] Prevent the changeDescriptionSink from crashing because of the refresh

backend/sirius-components-compatibility/pom.xml
=> [releng] Remove the unused dependency to EEF

CHANGELOG.adoc, doc/adrs/039_provide_a_variable_to_detect_the_environment.adoc, doc/adrs/040_add_support_for_a_post_selection.adoc
- [985] Add an ADR for the environment variable
- [988] Provide an ADR for the post selection support
=> New ADRs for the environment variable and the support of the post selection

backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/domain/DomainConverterTests.java
=> [test] Add basic unit tests for domain converter

backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IRepresentationPersistenceService.java, backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IEditingContextPersistenceService.java, backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/view/DynamicDiagramsTests.java
=> [test] Add basic dynamic diagram rendering test

CHANGELOG.adoc, backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/InvokeEdgeToolOnDiagramSuccessPayload.java, backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/InvokeNodeToolOnDiagramSuccessPayload.java, backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeEdgeToolOnDiagramEventHandler.java, backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java, backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls, backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls, backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/api/IIdentifierProvider.java, backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/ToolProvider.java, backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/WorkbenchSelection.java, backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/WorkbenchSelectionEntry.java, backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/compatibility/modeloperations/ChildModelOperationHandler.java, backend/sirius-components-representations/src/main/java/org/eclipse/sirius/components/representations/Success.java, frontend/src/diagram/DiagramWebSocketContainer.tsx, frontend/src/diagram/DiagramWebSocketContainer.types.ts, frontend/src/diagram/operations.ts
https://github.com/eclipse-sirius/sirius-components/issues/988
Introduce new concepts: WorkbenchSelection and WorkbenchSelectionEntry.
The Success of an operation can now contains a new parameter named
'newSelection' and containing a WorkbenchSelection.
=> [988] Add support for a post selection

CHANGELOG.adoc, doc/adrs/041_add_the_ability_to_contribute_additional_services_to_the_EMFQueryService.adoc
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1052
=> [1052] Add an ADR for the contribution of additional services in the EMFQueryService

backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/query/EMFQueryService.java, backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/query/api/IQueryJavaServiceProvider.java, backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/query/EMFQueryServiceTests.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1052
=> [1052] Add the ability to contribute additional services in the EMFQueryService

.github/workflows/build.yml, scripts/check-coverage.jsh
=> [test] Ensure that a minimal global code coverage is respected

CHANGELOG.adoc, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/LayoutConfiguratorRegistry.java, doc/adrs/044_use_border_node_snap_to_container_algorithm.adoc, frontend/src/diagram/DiagramWebSocketContainer.tsx, frontend/src/diagram/palette/ContextualPalette.tsx, frontend/src/diagram/sprotty/DependencyInjection.ts, frontend/src/diagram/sprotty/Diagram.types.ts, frontend/src/diagram/sprotty/DiagramServer.tsx, frontend/src/diagram/sprotty/__tests__/borderNodes.test.ts, frontend/src/diagram/sprotty/__tests__/siriusWebDiagram.ts, frontend/src/diagram/sprotty/convertDiagram.tsx, frontend/src/diagram/sprotty/siriusDragAndDropMouseListener.ts, frontend/src/diagram/sprotty/utils/geometry.ts, frontend/src/diagram/sprotty/utils/geometry.types.ts
Bug: https://github.com/eclipse-sirius/sirius-components/issues/956
Signed-off-by: Laurent Fasani <laurent.fasani@obeo.fr>
...
...
...
...
=> Improve the layout of border nodes

CHANGELOG.adoc, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ELKDiagramConverter.java, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/LayoutConfiguratorRegistry.java, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/BorderNodesOnSide.java, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/IncrementalLayoutEngine.java, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/provider/BorderNodeLabelPositionProvider.java, backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/BorderNodePositionTests.java, frontend/src/diagram/palette/ContextualPalette.tsx, frontend/src/diagram/sprotty/convertDiagram.tsx, frontend/src/diagram/sprotty/resize/siriusResize.ts, frontend/src/diagram/sprotty/siriusDragAndDropMouseListener.ts
- [ X ] New feature or improvement
...
...
...
...
=> [1071] Support the border node label display

frontend/src/workbench/Site.tsx
Bug: https://github.com/eclipse-sirius/sirius-components/issues/693
...
...
...
...
=> [693] Fix scrolling regression inside the panels

CHANGELOG.adoc, backend/sirius-components-collaborative-forms/src/main/resources/schema/form.graphqls, backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/Link.java, backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/LinkComponent.java, backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/LinkComponentProps.java, backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/WidgetComponent.java, backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/description/LinkDescription.java, backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/elements/LinkElementProps.java, backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/renderer/FormComponentPropsValidator.java, backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/renderer/FormElementFactory.java, backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/renderer/FormInstancePropsValidator.java, frontend/src/form/Form.types.ts, frontend/src/form/FormEventFragments.ts, frontend/src/form/FormEventFragments.types.ts, frontend/src/properties/Group.tsx, frontend/src/properties/propertysections/LinkPropertySection.tsx, frontend/src/properties/propertysections/LinkPropertySection.types.ts
- [X ] New feature or improvement
#695 
Add a Link widget to be able to display hyperlinks as widgets in properties views.
...
...
=> [695] Add Link widget

backend/sirius-components-collaborative-diagrams/pom.xml, backend/sirius-components-diagrams-layout/pom.xml, backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/DiagramLayoutTests.java, backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/IncrementalLayoutTests.java, backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DefaultTestDiagramDescriptionProvider.java, backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/TestDiagramCreationService.java, backend/sirius-components-diagrams-layout/src/test/resources/diagrams/bpmn.json, backend/sirius-components-diagrams-layout/src/test/resources/diagrams/domain.json, backend/sirius-components-diagrams-layout/src/test/resources/diagrams/topography_with_autolayout.json, backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/DiagramAssert.java, backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/DiagramAssertions.java, backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/NodeAssert.java, backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/PositionAssert.java, backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/edge/EdgeBuilder.java, backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/node/ImageNodeBuilder.java, backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/node/ListItemNodeBuilder.java, backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/node/ListNodeBuilder.java, backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/node/NodesBuilder.java
=> [test] Add tests for the incremental layout engine

.github/workflows/pull-request.yml, scripts/check-changelog.js, scripts/check-copyright.js
=> [releng] Perform some automatic checks on pull requests

CHANGELOG.adoc, backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/compatibility/properties/PropertiesDefaultDescriptionProvider.java, doc/adrs/050_add_support_for_multiple_selection_entries_in_the_details_view.adoc, frontend/src/diagram/DiagramWebSocketContainer.tsx, frontend/src/diagram/DiagramWebSocketContainerMachine.ts, frontend/src/diagram/sprotty/DependencyInjection.ts, frontend/src/diagram/sprotty/DiagramServer.tsx, frontend/src/form/FormWebSocketContainer.tsx, frontend/src/properties/Properties.tsx, frontend/src/properties/Properties.types.ts, frontend/src/properties/PropertiesWebSocketContainer.tsx, frontend/src/properties/propertysections/TextfieldPropertySection.tsx, frontend/src/properties/propertysections/TextfieldPropertySectionMachine.ts, frontend/src/representations/RepresentationsWebSocketContainer.tsx, frontend/src/tree/Tree.tsx, frontend/src/tree/TreeItem.tsx, frontend/src/workbench/Site.tsx
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1112
=> [1112] [1116] [1117] Improve support for multiple selection entries in the workbench

doc/how-to/how-to.adoc, doc/reference/reference.adoc
=> [doc] Add some documentation in order to start integrating Sirius Components

frontend/src/properties/propertysections/CheckboxPropertySection.tsx, frontend/src/properties/propertysections/CheckboxPropertySection.types.ts, frontend/src/properties/propertysections/RadioPropertySection.tsx, frontend/src/properties/propertysections/RadioPropertySection.types.ts, frontend/src/properties/propertysections/__tests__/CheckboxPropertySection.test.tsx, frontend/src/properties/propertysections/__tests__/RadioPropertySection.test.tsx, frontend/src/properties/propertysections/__tests__/__snapshots__/CheckboxPropertySection.test.tsx.snap, frontend/src/properties/propertysections/__tests__/__snapshots__/RadioPropertySection.test.tsx.snap
- Improved the typing of the RadioPropertySection and the CheckboxPropertySection
- Add unit tests using @testing-library/react
=> [test] Add unit tests for the Property Sections 

frontend/src/form/FormEventFragments.types.ts, frontend/src/properties/PropertiesWebSocketContainer.tsx
Improve the typing of PropertiesWebSocketContainer
=> [cleanup] Improve the typing of PropertiesWebSocketContainer

CHANGELOG.adoc, backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IEditingContextActionHandler.java, backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IEditingContextActionProvider.java, backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/dto/EditingContextAction.java, backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/dto/GetEditingContextActionsInput.java, backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/dto/GetEditingContextActionsSuccessPayload.java, backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/dto/InvokeEditingContextActionInput.java, backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/dto/InvokeEditingContextActionSuccessPayload.java, backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/handlers/GetEditingContextActionsEventHandler.java, backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/handlers/InvokeEditingContextActionEventHandler.java, backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls, doc/adrs/052_add_support_for_editing_context_actions.adoc, frontend/src/onboarding/NewDocumentArea.tsx, frontend/src/onboarding/NewDocumentArea.types.ts, frontend/src/onboarding/OnboardArea.tsx
closes https://github.com/eclipse-sirius/sirius-components/issues/1146
This PR adds support for Editing Context action.
=> [1146] Add Support for Editing Context Action

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.adoc
=> [1165] Improve the pull request template

backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/DiagramLayoutTests.java, backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DefaultTestDiagramDescriptionProvider.java, backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DiagramELKLayoutTest.java, backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/TestLayoutDiagramBuilder.java
It fixes the edge rendering in tests.
=> [test] Fix the edge rendering in tests

scripts/check-copyright.js
Signed-off-by: Florian Barbin <florian.barbin@obeo.fr>
=> [releng] Exclude removed files from the list to check copyrights

backend/sirius-components-representations/src/main/java/org/eclipse/sirius/components/representations/WorkbenchSelection.java, backend/sirius-components-representations/src/main/java/org/eclipse/sirius/components/representations/WorkbenchSelectionEntry.java
=> [1179] Make WorkbenchSelection and WorkbenchSelectionEntry serializable

doc/adrs/053_add_support_for_form_descriptions_in_the_view_converter.adoc
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1152
Signed-off-by: Florian Barbin <florian.barbin@obeo.fr> …
=> [doc] Update ADR to support textfield editing

backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/FormDescriptionEditorCreationService.java, backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/FormDescriptionEditor.java, backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorComponent.java
=> [1169] Fix FormDescriptionEditor representation name

CHANGELOG.adoc, backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/export/svg/DiagramExportService.java, backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/export/svg/EdgeExportService.java, backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/export/svg/NodeAndContainerId.java, backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/export/svg/NodeExportService.java, backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/export/DiagramExportServiceTests.java, backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/Bounds.java, backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/Geometry.java, backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/PointOnRectangleInfo.java, backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/RectangleSide.java, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/BorderNodesOnSide.java, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/IncrementalLayoutEngine.java, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/provider/BorderNodeLabelPositionProvider.java, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/provider/EdgeLabelPositionProvider.java, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/provider/NodeLabelPositionProvider.java, backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/updater/OverlapsUpdater.java
1. Create a Topography diagram
2. Export the Topography diagram to SVG
3. The generated SG should look like the Topography diagram
=> Fix the svg export for an empty diagram and a diagram containing edges

.github/workflows/build.yml
=> [fix] Force the ci to retrieve node 16.15.0

CHANGELOG.adoc, doc/adrs/062_switch_to_a_monorepo_layout.adoc, doc/adrs/063_simplify_the_sprotty_integration.adoc
=> [doc] Add an ADR for the switch to a monorepo layout

CHANGELOG.adoc, frontend/src/workbench/Site.tsx
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1308
_Please describe here the various use cases to test this …
=> [1308] Fix the vertical overflow issue on the view header

doc/adrs/061_add_support_for_flexbox_container_on_form_description.adoc
=> [doc] Update ADR-061 to fix number in description

CHANGELOG.adoc, packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ButtonWidget.tsx, packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx, packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.types.ts, packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx, packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetOperations.tsx, packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/icons/Button.tsx, packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/form/ButtonImageURLDataFetcher.java
=> [1273] Add support for button widget on FormDescriptionEditors

CHANGELOG.adoc, doc/adrs/067_inject_platform_beans_in_services.adoc, packages/emf/backend/sirius-components-interpreter/src/main/java/org/eclipse/sirius/components/interpreter/AQLInterpreter.java, packages/emf/backend/sirius-components-interpreter/src/test/java/org/eclipse/sirius/components/interpreter/AQLInterpreterTests.java, packages/emf/backend/sirius-components-interpreter/src/test/java/org/eclipse/sirius/components/interpreter/TestServices.java, packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewConverter.java, packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicDiagramsTests.java, packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicFormsTests.java
- Allow the AQL intepreter to user existing instances for its services
- Use auto-wired instances for the Java services used by studios
_Please describe here the various use cases to test …
=> Add support for injecting platform services/beans into Java service classes used by studios

CHANGELOG.adoc, packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverterSwitch.java
[1287] Fix missing createChild call on VariablaManager
Bug: #1287
There is no end-user scenario. It just fix a potential code issue
=> [1287] Fix missing createChild call on VariableManager

packages/forms/frontend/sirius-components-forms/src/propertysections/CheckboxPropertySection.tsx
=> [fix] Fix Form Representation related warning messages

packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx, packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.types.ts, packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/LabelWidget.tsx, packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx, packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetOperations.tsx
=> [1275] Add support for Label widget in Form Description Editor

CHANGELOG.adoc, packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnTwoDiagramElementsToolEventHandler.java, packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/EdgeDescription.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1341
Signed-off-by: Arthur Daussy <arthur.daussy@obeo.fr>
=> [1341] Expose source and target node variables during EdgeTool execution

CHANGELOG.adoc, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/BarChartDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ButtonDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/CheckboxDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/LabelDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/LinkDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ListDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/MultiSelectDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/PieChartDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/RadioDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/SelectDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/TextAreaDescriptionItemProvider.java, packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/TextfieldDescriptionItemProvider.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1347 …
=> [1347] Fix conditional styles menu items

CHANGELOG.adoc, packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/ListComponent.java, packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.tsx, packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicFormsTests.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1349 …
=> [1349] Fix Form representation scrolling on Y axis

CHANGELOG.adoc, packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1356
Signed-off-by: Arthur Daussy <arthur.daussy@obeo.fr> …
=> [1356] SemanticCandidates expression bypassed on Unsynchronized nodes
