src/components/main/Main.js
src/components/projects/ProjectHeaderCard.js
src/components/projects/ProjectRepresentationsListCard.js
src/components/projects/ProjectSemanticResourcesListCard.js
src/components/projects/ProjectSummaryCard.css
src/components/projects/ProjectSummaryCard.js
src/components/projects/ProjectsListCard.js
src/components/projects/project/ProjectView.css
src/components/projects/project/ProjectView.js

This commit will add a new page displaying the details of one project.
A link has been added from both the dashboard and the list of projects
to a page showing a project.
A project is displayed using the ProjectView component which uses both a
ProjectRepresentationsListCard and a ProjectSemanticResourcesListCard.
On top of the page, the details of the project itself will be visible in
the ProjectHeaderCard component.
Bug: https://github.com/eclipse/sirius-components/issues/6

Display one project

---

src/components/dashboard/DashboardView.js
src/components/main/Main.js
src/components/projects/ProjectsListCard.js
src/components/projects/listprojects/ListProjectsView.js
src/components/projects/project/ProjectView.js
src/containers/dashboard/DashboardViewStateContainer.js
src/containers/projects/ListProjectsViewStateContainer.js
src/containers/projects/ProjectViewStateContainer.js

This commit will add new stateful components which will be used to hold
the state for the user interface and communicate with the server. The
static data have been removed and the user interface is now computed
from the responses of the server.
The stateful containers, which can not be easily reused have been placed
in a dedicated folder named containers. This way, reusable and non
reusable components can easily be identified.
Bug: https://github.com/eclipse/sirius-components/issues/7

Connect the front-end with the back-end

---

src/common/dispatcherCreator.js
src/components/dashboard/DashboardView.js
src/components/dashboard/DashboardViewDispatcher.js
src/components/dashboard/DashboardViewFiniteStateMachine.js
src/components/projects/listprojects/ListProjectsViewDispatcher.js
src/components/projects/listprojects/ListProjectsViewFiniteStateMachine.js
src/components/projects/project/ProjectViewDispatcher.js
src/components/projects/project/ProjectViewFiniteStateMachine.js
src/containers/dashboard/DashboardViewStateContainer.js
src/containers/projects/ListProjectsViewStateContainer.js
src/containers/projects/ProjectViewStateContainer.js

This commit will add finite state machines in order to define all the
states and transitions that the stateful components can use. All the
transitions between the states have been extracted in reducers.
Dispatchers have been introduced in order to ensure that the transitions
and their results are matching the data of the finite state machine of
the component.
Bug: https://github.com/eclipse/sirius-components/issues/8

Define properly the states of stateful components

---

src/app.css
src/components/dashboard/DashboardView.css
src/components/dashboard/DashboardView.js
src/components/dashboard/__tests__/DashboardView.test.js
src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap
src/components/info/InfoCard.css
src/components/info/InfoCard.js
src/components/info/__tests__/InfoCard.test.js
src/components/info/__tests__/__snapshots__/InfoCard.test.js.snap

This commit will add new cards to the dashboard in order to display some
global information regarding the server. It will thus show the number of
projects available along with the number of viewpoints and metamodels.
The layout of the dashboard has been updated with the introduction of a
new kind of card, the InfoCard.
Bug: https://github.com/eclipse/sirius-components/issues/28

Update the dashboard will additional data

---

docs/knowledgebase.adoc
src/common/errors.js
src/components/error/ErrorBoundary.js
src/components/main/Main.js

This commit will add a new component, the ErrorBoundary in order to
catch unexpected errors during the rendering.
Bug: https://github.com/eclipse/sirius-components/issues/27

Handle rendering errors

---

src/components/cards/Card.css
src/components/projects/ProjectRepresentationsListCard.js
src/components/projects/ProjectSemanticResourcesListCard.js
src/components/projects/project/__tests__/ProjectView.test.js
src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap
src/components/workflow/WorkflowCard.js
src/containers/projects/__tests__/ProjectViewStateContainer.test.js

This commit improves the support for partially empty states. As such,
we will now properly handle a project without any semantic resources or
without any representations.
Bug: https://github.com/eclipse/sirius-components/issues/39

Improve support for empty states

---

package.json

Use double quotes instead of single quotes in order to make
prettier work on windows.
Bug: https://github.com/eclipse/sirius-components/issues/47
Signed-off-by: Guillaume Coutable <guillaume.coutable@obeo.fr>

Issue on using prettier cli on windows

---

src/components/dashboard/DashboardView.css

Make all the projects card in the dashboard have the same height.
Bug: https://github.com/eclipse/sirius-components/issues/55

All project cards should have the same height

---

src/components/app/App.css
src/components/app/App.js
src/components/aside/Aside.css
src/components/main/Main.css

Both the navbar and the sidebar can be hidden using the query parameter
fullscreen with the value true, for example with the following URL:
https://domain.tld/projects/test?fullscreen=true
Bug: https://github.com/eclipse/sirius-components/issues/29
Signed-off-by: Stéphane Bégaudeau stephane.begaudeau@obeo.fr>

Add the ability to hide the sidebar

---

docs/development.adoc
src/index.js

While building the project, we can now specify the path where the code
will be deployed in order to make the loading of resources and the
router work.
If you want to deploy the code at the path /workflow, you would have to
set the environment variable PUBLIC_URL to /workflow before the build.
Bug: https://github.com/eclipse/sirius-components/issues/93

Add support for deployment at a specific path

---

backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/UploadDocumentEventHandlerTestCases.java

[cleanup] Use StandardCharsets.UTF_8 instead of refering it by name

---

backend/sirius-web-graphql-utils/src/main/java/org/eclipse/sirius/web/graphql/utils/providers/GraphQLScalarConverter.java

The type is deprecated and planned for removal in the latest version
of GraphQL Java, and we do not actually use it in our schema.
See commit message.
See commit message.
The existing tests should be enough to ensure the change does not cause any regression.

[cleanup] Remove GraphQLLong from GraphQLScalarConverter

---

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/representations/SiriusRepresentationDescriptionProvider.java

Fixes #188
Bug: https://github.com/eclipse-sirius/sirius-components/issues/188
Signed-off-by: Mélanie Bats <melanie.bats@obeo.fr>
See https://github.com/eclipse-sirius/sirius-components/issues/188
Do not try to transpile sequence diagram descriptions found in VSMs, we do not support them and the resulting conversion is meaningless.

[188] Ignore Sequence Diagram in VSMs

---

frontend/src/diagram/DiagramWebSocketContainer.tsx
frontend/src/index.ts
frontend/src/views/edit-project/EditProjectLoadedView.tsx
frontend/src/views/edit-project/EditProjectView.tsx
frontend/src/views/edit-project/RepresentationArea.tsx

This commit is a first part of the refactoring to improve the reusability of
our representations. Additional contributions will define a clear contract
between the core parts of the application and representation components.
Bug: https://github.com/eclipse-sirius/sirius-components/issues/159
...
...
...
...

[159] Make the diagrams-related components easier to reuse

---

.github/workflows/build.yml

Try to speed up the builds by enabling caching of Node and Maven dependencies.
See:
* https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven#caching-dependencies
* https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs#example-caching-dependencies

[build] Cache Node and Maven dependencies for faster builds

---

frontend/.vscode/settings.json

This prevents some build errors when iterating in frontend source, and by normalizing the imports order automatically for everyone should make merge conflicts on these parts less frequent and easier to deal with.

[cleanup] Automatically organize imports on save in VS Code

---

backend/sirius-web-collaborative-diagrams-api/src/main/java/org/eclipse/sirius/web/collaborative/diagrams/api/IDiagramDescriptionService.java
backend/sirius-web-collaborative-diagrams-api/src/main/java/org/eclipse/sirius/web/collaborative/diagrams/api/IDiagramService.java
backend/sirius-web-collaborative-diagrams-api/src/main/java/org/eclipse/sirius/web/collaborative/diagrams/api/dto/DeleteFromDiagramInput.java
backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingConverter.java
backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/diagrams/DiagramDescriptionConverter.java
backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingConverterTestCases.java
backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/diagrams/NoOpEditService.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/description/EdgeDescription.java
backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTestCases.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramDescriptionService.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramService.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/graphql/MutationDeleteFromDiagramDataFetcher.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/messages/CollaborativeDiagramMessageService.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/messages/ICollaborativeDiagramMessageService.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/messages/MessageConstants.java
backend/sirius-web-spring-collaborative-diagrams/src/main/resources/messages/sirius-web-spring-collaborative-diagrams.properties
backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/NoOpCollaborativeDiagramMessageService.java
backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/NoOpDiagramService.java
frontend/src/diagram/DiagramWebSocketContainer.tsx
frontend/src/diagram/reducer.ts
frontend/src/diagram/sprotty/WebSocketDiagramServer.tsx

#119
Call the delete handler on an edge when the remove tool is triggered.
* Diagram refresh
* Delete tool
* A test case that delete all edges in Robot topography diagram
* On Robot sample, 
* create a topography diagram
* select an edge
* use the palette delete tool 
* **we expect a diagram refresh without this edge**
* select another edge
* use the [SUPPR] keyboard
* **we expect a diagram refresh without this edge**

Support for delete edge from diagram tool

---

backend/sirius-web-collaborative-forms-api/src/main/java/org/eclipse/sirius/web/collaborative/forms/api/dto/UpdateWidgetFocusSuccessPayload.java
backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationUpdateWidgetFocusDataFetcher.java
backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/FormEventProcessor.java

As there was no success payload with the
MutationUpdateWidgetFocusDataFetcher, the response for the
updateWidgetFocus request was an error paylod with an error message.
Bug: https://github.com/eclipse-sirius/sirius-components/issues/161
Signed-off-by: Steve Monnier <steve.monnier@obeo.fr>
...
...
...
...

[161] Add success payload for MutationUpdateWidgetFocusDataFetcher

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/DocumentService.java

Optimize DocumentService.getBytes() in the case when "exporting" as JSON (typically when exporting a whole project archive).

[261] Avoid unneeded work in DocumentService.getBytes()

---

frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbarContextMenu.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/303
...
...
...
...

[303] Remove the link to modelers from the project context menu

---

backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeComponent.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeSizeProvider.java

Change-Id: If25f64661b655d71b8776796f66249dab13e0e22
Signed-off-by: William Piers <william.piers@obeo.fr>
See #300
Recompute the size of each node without children on refresh. This way nodes with conditional sizes are reevaluated.
The solution cannot apply to containers as their size is computed by ELK accordingly to its content and the incremental layout, in its current state, cannot do that.

[300] Fix size computation

---

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/LabelStyleDescriptionConverter.java
backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/AllSiriusWebCompatibilityTests.java
backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/diagrams/LabelStyleDescriptionConverterTestCases.java

- handle iconPath property from odesign files to be able to display
icons specified in odesign files
Bug: https://github.com/eclipse-sirius/sirius-components/issues/314
This PR handles the 'iconPath' property from odesign files
- [ x I have signed the [Contributor License Agreement](http://www.eclipse.org/legal/CLA.php).

[314] Handle iconPath property

---

backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramCreationService.java

[360] Restore the use of the auto layout on diagram creation

---

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/diagrams/ToolProvider.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/EdgeComponent.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/description/EdgeDescription.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/tools/CreateEdgeTool.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeEdgeToolOnDiagramEventHandler.java

The work is not finished (no tests).
I've added 2 new variables. The initial request was to have them available in the context of labels computation; then we had a second request to make them available to edge delete tool. While trying to add them to all relevant locations I note that we already have 2 variables with the same values (but different names) in the context of edge creation (`InvokeEdgeToolOnDiagramEventHandler`).
I find the names I used (`semanticEdgeSource` & `semanticEdgeTarget`) more explicit than the ones we already have for edge creation (just `source` and `target`), but those are the ones used by Sirius Desktop (see `org.eclipse.sirius.diagram.description.tool.impl.ToolFactoryImpl.createEdgeCreationDescription()`).

[341] Add useful variables to edge-related expressions

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditService.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditingContextEPackageService.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditingContextSearchService.java
backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/PageInfoTypeProvider.java

Building an EMF EPackageRegistryImpl with a "delegate" does not seem
to work like the code expects it to. Calling values() on such an
EPackage does not return any of the packages in the delegate. In this
case this makes all the globaly registered EPackages invisible to this
code. As this is called from e.g.
EditingContextRepresentationDescriptionsDataFetcher this makes it
impossible to create a new representation as the target CLASS_ID is
never properly resolved

[333] Fix package delegation logic

---

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ColorDescriptionConverter.java
backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ContainerMappingStyleProvider.java
backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingStyleProvider.java
backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/LabelStyleDescriptionConverter.java
backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeMappingStyleProvider.java
backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/diagrams/ColorDescriptionConverterTestCases.java

Also adjust some APIs to reduce the number of unneeded calls to
VariablesManager.getVariables() which is not free when repeated in hot
loops like during a render.

[407] Add support for edges' sizeComputationExpression

---

frontend/src/diagram/sprotty/DependencyInjection.ts
frontend/src/diagram/sprotty/WebSocketDiagramServer.tsx

https://github.com/eclipse-sirius/sirius-components/issues/426
Hide the contextual palette when a zoom or scroll action is initiated.

[426] Hide the contextual palette when zooming or scrolling/panning

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/diagrams/CanCreateDiagramPredicate.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/TargetNodesProvider.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java

With these fixes and a sample `View` definition (programmatically defined to workaround currentl limitations in our properties view), I get the following result on the sample Robot:
The edges in black are domain-based, and represent `DataFlow` elements.
The edges in blue are reference-based and represent the containment between `CompositeProcessors` and `Processors`.
Here is the full definition of the `View` model used, in Java:
```java
private View getSampleView() {
View view = ViewFactory.eINSTANCE.createView();
DiagramDescription diagramDescription = ViewFactory.eINSTANCE.createDiagramDescription();
diagramDescription.setName("Flow Edges Test"); //$NON-NLS-1$
diagramDescription.setDomainType("System"); //$NON-NLS-1$
diagramDescription.setTitleExpression("aql:'Flow Edges'"); …
```

[412] Fix edge handling in ViewConverter

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/CanonicalBehaviors.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/DynamicRepresentationDescriptionService.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/StylesFactory.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java

Add support for:
- node and edge creation tools
- initial name for newly created elements
- direct-edit
- deletion
The first commit in the series, "dep: fixes for edge handling and direct edit on diagrams" is needed for testing, but it's actually a squash of the commits in PRs #413 https://github.com/eclipse-sirius/sirius-components/pull/421 so should not be merged as part of this.
To test this patch, the easiest way is to also get the programmatically defined View definition mentioned in PR #413 .
The result can be seen here: https://www.youtube.com/watch?v=ZWfNVqORGrU

[411] Add canonical behaviors to dynamic view definitions

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditingContextEPackageService.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/DynamicRepresentationDescriptionService.java
backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/NoOpDocumentRepository.java
backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/repositories/IDocumentRepository.java
backend/sirius-web-persistence/src/main/resources/db/sirius-web-named-queries.properties

@sbegaudeau I'm not entirely sure about the new API this introduces: `Iterable<DocumentEntity> findAllByType(String name, String uri)`.
Another option would be to have explicit `findAllDomainDefinitions` and `findAllViewDefinitions`, but that seems overly specific and IMO `IDocumentRepository` should stay agnostic about the kind of documents we store. If tomorrow we want to hadd new kinds which are treated somewhat specially by other parts of the system, we shouldn't have to touch this API every time.
OTOH, the `(String name, String uri)` also leak EMF-specific concepts, even if they are just strings here. Between the name (`findAll**ByType**`) and these arguments, it implicitly introduces a notion of document type identified by name/uri, which we do not have at the moment.
Otherwise the …

[397] Be more specific when looking for potential domain or view documents

---

backend/sirius-web-domain-edit/src/main/java/org/eclipse/sirius/web/domain/provider/EntityItemProvider.java
backend/sirius-web-domain-edit/src/main/resources/plugin.properties
backend/sirius-web-domain/plugin.xml
backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/DomainPackage.java
backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/Entity.java
backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/DomainPackageImpl.java
backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/EntityImpl.java
backend/sirius-web-domain/src/main/resources/model/domain.ecore
backend/sirius-web-domain/src/main/resources/model/domain.genmodel
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java

The only "tricky" part of the PR is how `DomainConverter` handles inheritance. It might be a little more complex than needed for handling single inheritance, but the code is 99% ready to support mulitple inheritance when we add it.
The rest is trivial changes in the `ecore` and the corresponding regen.

Domain DSL: Add support for single inheritance and abstract entities

---

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/AbstractNodeMappingConverter.java
backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/AbstractNodeMappingStyleProvider.java
backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/LabelStyleDescriptionConverter.java
backend/sirius-web-diagrams-layout/pom.xml
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/ELKDiagramConverter.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutConfiguratorRegistry.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutOptionValues.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/TextBoundsService.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/IncrementalLayoutDiagramConverter.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/IncrementalLayoutEngine.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/data/LabelLayoutData.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/NodeLabelPositionProvider.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/NodePositionProvider.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/NodeSizeProvider.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/updater/ContainmentUpdater.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/ListItemNodeStyle.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/ListNodeStyle.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/NodeType.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/LabelType.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeComponent.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/INodeStyleDeserializer.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/graphql/DiagramTypesProvider.java
frontend/src/diagram/operations.ts
frontend/src/diagram/sprotty/DependencyInjection.ts
frontend/src/diagram/sprotty/convertDiagram.tsx
frontend/src/diagram/sprotty/siriusDragAndDropMouseListener.ts
frontend/src/diagram/sprotty/views/LabelView.tsx
frontend/src/diagram/sprotty/views/ListItemView.tsx
frontend/src/diagram/sprotty/views/ListView.tsx
frontend/src/index.ts

- Creates a node list when the Sirius container mapping style is "LIST"
- Creates a node list item when a Sirius node mapping style represents a
simple figure (ellipse, lozenge, square)
- Improves ELK configuration to support these node types
- Updates ELK dependency to 0.7.1 because a bug prevents
NodeSizeConstraints option to be correctly applied
- Provides an OS aware minimum size for empty labels.
Bug: eclipse-sirius/sirius-components#418
Signed-off-by: Guillaume Coutable <guillaume.coutable@obeo.fr>
https://github.com/eclipse-sirius/sirius-components/issues/418
This PR provides the first support of NodeList and NodeListItem for sirius-component with the ELK configuration.
...
Does not work well with the incremental layout yet.
- From the Model explorer :
- Creates an empty model
- …

[418] Add the support for list container

---

backend/sirius-web-collaborative-api/src/main/java/org/eclipse/sirius/web/collaborative/api/services/IEditingContextEventProcessorFactory.java
backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/NoOpRepresentationService.java
backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/repositories/IRepresentationRepository.java
backend/sirius-web-persistence/src/main/resources/db/sirius-web-named-queries.properties
backend/sirius-web-persistence/src/test/java/org/eclipse/sirius/web/persistence/repositories/JPAConfiguration.java
backend/sirius-web-persistence/src/test/java/org/eclipse/sirius/web/persistence/repositories/RepresentationRepositoryIntegrationTestCases.java
backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/representations/IRepresentationService.java
backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationService.java
backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/representations/NoOpDocumentRepository.java
backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/representations/NoOpRepresentationRepository.java
backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/NoOpRepresentationService.java
backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessor.java
backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessorFactory.java
backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessorRegistry.java
backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/NoOpRepresentationService.java

https://github.com/eclipse-sirius/sirius-components/issues/452
It adds a service used to cleanup representations that are not bound to an object.

Cleanup unbound representation

---

backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/EdgeComponent.java
backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTestCases.java

The set of keys used previously was not enough, as it would compute
the same id for two edge between the same source and target elements
but from different EdgeDescriptions. Such a duplicate id would crash
the frontend inside Sprotty.

🐛 [fix] Fix potential duplicate id on edges

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java

The previous condition did not account for the sentinel element.

🐛 [480] Fix inheritance support in DomainConverter

---

backend/sirius-web-representations/src/main/java/org/eclipse/sirius/web/representations/VariableManager.java

It is not used for anything and can cause memory leaks, as children
VariableManagers created for temporary computations were forever
referenced by the parent they were created from.

🧹 [cleanup] Remove VariableManager.children

---

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/forms/ViewExtensionDescriptionConverter.java
backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/properties/FormRendererTestCases.java

Bug: #325
Signed-off-by: j-barata <jean.barata@thalesgroup.com>
#325
...
...
...

[325] Move ViewExtensionDescriptionConverter to sirius-web-compatibility

---

backend/sirius-web-diagrams-layout/pom.xml

In its plug-in dependencies, ELK requires guava [15,19), but, since a
recent version ELK uses guava Streams which have been introduced in
guava 21.
To prevent ClassNotFoundException to occur because of guava Streams we
force the use of guava 30.
We will be able to revert this commit when ELK 0.8.0 will be released

[fix] Force the use of guava 30

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditService.java
frontend/src/modals/new-object/NewObjectModal.tsx

https://github.com/eclipse-sirius/sirius-components/issues/532
- Makes the CreateChildEventHandler returning an ErrorPayload when the
child that has been created has no owner.
- Handles ErrorPayload in NewObjectModal
1. Creates a view model, a diagram description, and a node description
2. Creates a first node style under the node description
3. Tries to create a second node style under the  same node description
The modal used to create the node description child should still be displayed, and the Material-UI Snackbar should appear with an error message.

[532] Improve explorer child creation

---

frontend/src/tree/TreeItem.tsx

Make the labels more compact and readable, while still preserving access to the type information when needed.
* Left: before (e.g. "Processor Radar_Capture")
* Right: after ("Radar_Capture" with "Processor" in the tooltip)

[572] Move the object type name in a tooltip for tree items

---

backend/sirius-web-emf/pom.xml
backend/sirius-web-spring-starter/pom.xml
backend/sirius-web-spring-starter/src/main/java/org/eclipse/sirius/web/starter/SiriusWebStarterConfiguration.java

In order to prepare for the move of our business code from Sirius Components to Sirius Web, this PR will reduce the dependencies provided by the Sirius Components starter project.

Remove dependencies from the sirius-web-spring-starter project

---

backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/updater/ContainmentUpdater.java

- [550] Consider the same padding as ELK's in the incremental layout
- [550] Refactor for clarity
- [550] Only change container size if it is too small to hold its content

Avoid resetting edge's routing in some cases when it is not needed

---

frontend/src/diagram/DiagramWebSocketContainer.tsx
frontend/src/diagram/sprotty/WebSocketDiagramServer.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/432
...
...
...
...

[432] Fix direct edit tool invocation from the palette

---

frontend/src/properties/PropertiesWebSocketContainer.tsx
frontend/src/validation/ValidationWebSocketContainer.tsx

https://github.com/eclipse-sirius/sirius-components/issues/602
- It prevents the properties view to display the "empty" state message
while there is a selection
- It removes the empty state message because it is not needed

[602] Improve the properties and validation view

---

frontend/src/core/contextmenu/ContextMenu.module.css

Bug: https://github.com/eclipse-sirius/sirius-components/issues/610
This PR fixes the "Download" underlined menu entry.
No side effects

[610] Fix "Download" menu entry underlined

---

backend/sirius-web-domain-edit/.settings/org.eclipse.core.resources.prefs
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainValidator.java
backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextEPackageService.java
backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchService.java

- [cleanup] Simplify domain inheritance conversion code
- [cleanup] Refactor domain conversion code
- [cleanup] Refactor EditingContextEPackageService
- [cleanup] Log a warning when multiple domains/packages have the same nsURI
- [fix] Ignore documents which could not be loaded properly

Improve DomainConverter

---

frontend/src/core/contextmenu/ContextMenu.module.css

This reverts commit b18570719a784be59b9c101fbcc25dc02dfda1d8.
Bug: https://github.com/eclipse-sirius/sirius-components/issues/610

[610] Revert the previous commit to remove the global CSS rule

---

backend/sirius-web-collaborative-forms-api/src/main/java/org/eclipse/sirius/web/collaborative/forms/api/dto/EditMultiSelectInput.java
backend/sirius-web-collaborative-forms-api/src/main/java/org/eclipse/sirius/web/collaborative/forms/api/dto/EditMultiSelectSuccessPayload.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/MonoValuedNonContainmentReferenceIfDescriptionProvider.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/MultiValuedNonContainmentReferenceIfDescriptionProvider.java
backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/MultiSelect.java
backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/components/MultiSelectComponent.java
backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/components/MultiSelectComponentProps.java
backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/components/WidgetComponent.java
backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/description/MultiSelectDescription.java
backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/elements/MultiSelectElementProps.java
backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/renderer/FormComponentPropsValidator.java
backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/renderer/FormElementFactory.java
backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/renderer/FormInstancePropsValidator.java
backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/FormTypesProvider.java
backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationEditMultiSelectDataFetcher.java
backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditMultiSelectEventHandler.java
backend/sirius-web-spring-graphql/src/main/java/org/eclipse/sirius/web/spring/graphql/ws/handlers/StartMessageHandler.java
frontend/src/form/Form.types.ts
frontend/src/form/FormEventFragments.ts
frontend/src/form/FormEventFragments.types.ts
frontend/src/index.ts
frontend/src/properties/Group.tsx
frontend/src/properties/propertysections/ListPropertySection.tsx
frontend/src/properties/propertysections/MultiSelectPropertySection.tsx
frontend/src/properties/propertysections/MultiSelectPropertySection.types.ts
frontend/src/properties/propertysections/RadioPropertySection.tsx
frontend/src/properties/propertysections/SelectPropertySection.tsx

https://github.com/eclipse-sirius/sirius-components/issues/428
Use the https://material-ui.com/components/selects/#multiple-select widget with the tag option to handle multi-valued references in the properties view.
When the widget is selected, a scrollable list of options is displayed to the user, and each option can be selected through a checkbox.
All multi-valued non-contained references are now displayed in the Properties View, even the `eOpposite` ones.

[428] Support for editing multi-valued references in the properties view

---

frontend/src/explorer/Explorer.module.css
frontend/src/properties/Properties.tsx
frontend/src/workbench/LeftSite.tsx
frontend/src/workbench/RightSite.tsx
frontend/src/workbench/RightSite.types.ts

#640
- Replaces Tabs by Accordion on side views
- Removes the overflow rule on explorer to let it be handled by the
accordion container.
- Fixes the overflow that could be displayed on the whole application.
- Removes the background-color rule on properties to make it the same as
its container.
- Move the Validation view to the left, under the Explorer view.

[640] Use accordions for the layout of the left and right sites

---

backend/sirius-web-interpreter/src/main/java/org/eclipse/sirius/web/interpreter/AQLInterpreter.java
backend/sirius-web-interpreter/src/main/java/org/eclipse/sirius/web/interpreter/SimpleCrossReferenceProvider.java
backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/EditingDomainFactory.java
backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchService.java
backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchServiceTests.java

See https://github.com/eclipse-sirius/sirius-components/issues/190
Install an ECrossReferenceAdapter directly on every EditingContext, and configure the AQL interpreter to use it as the source for eInverse().
See https://github.com/eclipse-sirius/sirius-components/issues/190
I have not (yet) added specific tests, so this should probably not be merged for now.

[190] Add support for inverse references navigation

---

frontend/src/modals/new-representation/NewRepresentationModal.tsx
frontend/src/modals/new-representation/NewRepresentationModalMachine.ts

Bug: #677
Updates  the name of the representation in the new representation dialog so that it matches the selected representation type, as long as the user doesn't modify the name field.

[677] Add new representation default name

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainValidator.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EMFValidationService.java

- This rule will return an error if two entities have the same name. The
case is ignored.
- Prevents all named attributes in Domain to have a validation error when
only one named attribute had one validation error.

[enh] Add a validation rule on domain name

---

backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/EdgeDescriptionItemProvider.java

Fixes #646.
Bug: https://github.com/eclipse-sirius/sirius-components/issues/646
...
...
...
...

[646] Fix default color for new edges in the View DSL

---

frontend/src/selection/SelectionDialogWebSocketContainer.tsx
frontend/src/workbench/RepresentationNavigation.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/559
Add data-testid attributes in SelectionDialogWebSocketContainer to be able to test it with Cypress

[559] Add data attributes in SelectionDialogWebSocketContainer

---

frontend/src/modals/new-document/NewDocumentModal.tsx
frontend/src/modals/new-document/NewDocumentModal.types.ts
frontend/src/modals/new-document/NewDocumentModalMachine.ts

This PR fixes the CreateDocumentModal which has not been updated when `StereotypeDescriptions` in the `EditingContext` have been paginated.

[fix] Fix the create document dialog

---

backend/sirius-web-spring-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
backend/sirius-web-spring-collaborative-forms/src/main/resources/schema/form.graphqls
backend/sirius-web-spring-collaborative-selection/src/main/resources/schema/selection.graphqls
backend/sirius-web-spring-collaborative-trees/src/main/resources/schema/tree.graphqls
backend/sirius-web-spring-collaborative-validation/src/main/resources/schema/validation.graphqls
backend/sirius-web-spring-collaborative/src/main/resources/schema/core.graphqls

Those schema will now act as the source of truth of the GraphQL API
used by Sirius Components. Applications integrating Sirius Components
should now follow the evolutions of those schemas in order to detect
changes in our GraphQL API.
Bug: https://github.com/eclipse-sirius/sirius-components/issues/671

[671] Add the GraphQL schemas of Sirius Components

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/MonoValuedNonContainmentReferenceIfDescriptionProvider.java

[fix] Fix erroneous error status when unsetting a mono-valued reference

---

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/diagrams/ToolProvider.java

* `container` is the (default) name for the variable used by Sirius Desktop to refer to the semantic element on which a node or container creation tool is invoked. See `{Node,Container}CreationCommandBuilder` and `ToolFactoryImpl.create{Node,Container}CreationDescription()` in Sirius Desktop.
* `element` plays the same role for the generic tools. See `GenericToolCommandBuilder` and  `ToolFactoryImpl.createToolDescription()`.

[719] Add support for the 'container' and 'element' compatibility variables

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditService.java
backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/EditingDomainFactory.java

Bug: https://github.com/eclipse-sirius/sirius-components/issues/729
Signed-off-by: Arthur Daussy <arthur.daussy@obeo.fr>
...
...
...
...

[729] Improve ResourceSet creation to be a IEditingDomainProvider

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/AQLInterpreterFactory.java

...
- Use a plain warning message when a class cannot be loaded instead of a stacktrace.
- Do not try to load a class when the extension uses ::-style reference (@pcdavid told me that there is no plan to support such references in SiriusW)
- Handle `NoClassDefFoundError`. In case extension classes reference Eclipse platform classes and crash
the startup process.
...
...

Improve warnings for Java extension loading errors

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java

Signed-off-by: Arthur Daussy <arthur.daussy@obeo.fr>
Bug: https://github.com/eclipse-sirius/sirius-components/issues/735
...
...
...
...

[735] Generic edge tool should not be added when a custom is provided

---

backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutConfiguratorRegistry.java

Image nodes have their labels on the outside, so the label width should not be considered by ELK when computing the width of the node itself, or it could lead to bounding boxes larger than needed with ugly side effects.

[747] Fix bounding box computation for images with wide labels

---

backend/sirius-web-domain-edit/src/main/java/org/eclipse/sirius/web/domain/provider/DomainItemProvider.java
backend/sirius-web-domain-edit/src/main/resources/plugin.properties
backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/Domain.java
backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/DomainPackage.java
backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/DomainImpl.java
backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/DomainPackageImpl.java
backend/sirius-web-domain/src/main/resources/model/domain.ecore
backend/sirius-web-domain/src/main/resources/model/domain.genmodel
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainValidator.java
backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/validation/DomainValidatorTests.java

It's a technical detail which can, and should, be derived
automatically from the name instead of delegating this responsibility
to the user.
The change also allows us to enforce the constraint that all EPackages
derived from domains will have an nsURI starting with `domain://`.

[740] Remove the explicit nsURI from Domain definitions

---

CHANGELOG.adoc
frontend/.vscode/tasks.json
frontend/tsconfig-noEmit.json

Provide a task that must be launched by hand (CMD+P in vscode).
Once launched, the task will display typescript errors in the problems view.

[cleanup] Add a task to display typescript errors in vscode problems

---

CHANGELOG.adoc
backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingConverter.java
backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/description/EdgeDescription.java
backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTests.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramQueryService.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/api/IDiagramQueryService.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/EditLabelEventHandler.java
frontend/src/diagram/sprotty/WebSocketDiagramServer.tsx
frontend/src/diagram/sprotty/__tests__/convertDiagram.test.ts
frontend/src/diagram/sprotty/convertDiagram.tsx

Selecting an edge now display an edit tool in the popup palette allowing
the user to rename the edge.
Bug: https://github.com/eclipse-sirius/sirius-components/issues/154
Signed-off-by: Steve Monnier <steve.monnier@obeo.fr>
...
...
...
...

[154] Add edit edge label support

---

CHANGELOG.adoc
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java

The Node.SELECTED_NODE and the NodeTool.SELECTED OBJECT
should be setup independently each other in invokeNodeTool.
...
...
...
...

Setup the Node.SELECTED_NODE and SELECTED OBJECT independently

---

backend/sirius-web-selection/pom.xml
backend/sirius-web-spring-collaborative-selection/pom.xml
backend/sirius-web-spring-collaborative-validation/pom.xml
backend/sirius-web-validation/pom.xml

Not all projects had properly been migrated to Spring Boot 2.5.6, this
commit fixes that

[releng] Switch some projects from Spring Boot 2.5.1 to 2.5.6

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java

Bug: https://github.com/eclipse-sirius/sirius-components/issues/154
Fix missing usage of mandatory labelEditHandler in edge conversion in ViewConverter

[154] Add edit edge label support - fix edge conversion in View

---

scripts/check-licenses

Example output:
```
Checking backend dependencies...
[main] INFO Querying Eclipse Foundation for license data for 187 items.
[main] INFO Found 142 items.
[main] INFO Querying ClearlyDefined for license data for 45 items.
[main] INFO Found 45 items.
Vetted license information was found for all content. No further investigation is required.
Checking frontend dependencies...
[main] INFO Querying Eclipse Foundation for license data for 745 items.
[main] INFO Found 33 items.
[main] INFO Querying ClearlyDefined for license data for 713 items.
[main] INFO Found 713 items.
License information could not be automatically verified for the following content:
npm/npmjs/-/jest-junit-reporter/1.1.0
npm/npmjs/-/jsdom/16.7.0
npm/npmjs/-/typescript/4.3.5
npm/npmjs/-/xstate/4.23.1 …
```

[releng] Add script to check license compatibility

---

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/forms/ViewExtensionDescriptionConverter.java

Signed-off-by: Denis Nikiforov <denis.nikif@gmail.com>
Property pages in our odesign files use property groups defined in a separate categories. We get NPE for such property groups.
It allows to use property groups defined in a separate categories.
No.
No.

[fix] Add support for property groups defined in a different category

---

backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/LabelComponent.java
backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererNodeTests.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramQueryService.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/api/IDiagramQueryService.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/EditLabelEventHandler.java

Label ids (computed in
AbstractNodeMappingConverter.getLabelIdProvider()) have a suffix
appended to their UUID, so we can not take the resulting string and
parse it directly.
Bug: https://github.com/eclipse-sirius/sirius-components/issues/852
...
...
...
...

[852] Fix regression on label ids

---

CHANGELOG.adoc
backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/forms/WidgetDescriptionConverter.java

This is not supposed to happen on well-formed odesign files, but in practice not all existing odesign files are well-formed/valid.

[fix] Fix potential NPE in logging code

---

backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/CanonicalBehaviors.java

In the most common case, the newly created semantic element should not
be inside the source element of the edge, but a sibling of that
element in the same parent.
For example when creation a Relation from Class A to Class B, the new
Relation instance would be in the enclosing Package, not inside A.

[fix] Fix the canonical domain-based edge creation tool

---

frontend/src/properties/Properties.tsx

Add a tooltip to the title of the details view, so that in the (common) case where the label is truncated the user can still get the full name of the selected object.
Before:
After:
A better solution would be to have a more compact label, maybe by replacing the type name with the corresponding icon (the type name could still be available as a tooltip of the icon) and/or to wrap it instead of truncate. It would require more work however, so in the meantime this seems like a quasi-free improvement.

[enh] Add a tooltip to always make the full label available

---

CHANGELOG.adoc
backend/sirius-web-compatibility/pom.xml

Switch to the recently released [Sirius Desktop 6.6.0](https://projects.eclipse.org/projects/modeling.sirius/releases/6.6.0).
It mostly contains bug fixes, and a single new feature. None of which should have any impact on us except making sure we follow the latest version of Sirius Desktop.

[845] Switch to Sirius Desktop 6.6.0

---

CHANGELOG.adoc
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewPropertiesConfigurer.java
backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/ConditionalNodeStyleItemProvider.java
backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/NodeStyleItemProvider.java
backend/sirius-web-view-edit/src/main/resources/plugin.properties
backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/NodeStyle.java
backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ConditionalNodeStyleImpl.java
backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/NodeStyleImpl.java
backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
backend/sirius-web-view/src/main/resources/model/view.ecore
backend/sirius-web-view/src/main/resources/model/view.genmodel

- [726] Add NodeStyle.sizeComputationExpression the the MM
- [726] Add property section to configure the size expression
- [726] Compute the dynamic size when creating the node style
- [cleanup] Remove log message from Result
#726 
Add a `sizeComputationExpression` to node styles in the View DSL, and use it to feed `NodeDescription.sizeProvider`.
https://user-images.githubusercontent.com/10608/144457549-fc6ac50a-f0db-4e61-96ce-dab3bfb7a195.mp4
...

View DSL: add support for computed size for nodes

---

CHANGELOG.adoc
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/NodeDescriptionItemProvider.java
backend/sirius-web-view-edit/src/main/resources/plugin.properties
backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/NodeDescription.java
backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/NodeDescriptionImpl.java
backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
backend/sirius-web-view/src/main/resources/model/view.ecore
backend/sirius-web-view/src/main/resources/model/view.genmodel

This is on top of https://github.com/eclipse-sirius/sirius-components/pull/857, the actual commits specific to this change are the last 3:
- [596] Add border nodes in the View DSL
- [596] Handle border nodes in viewconverter
- [596] Update the CHANGELOG

View DSL: Add support for defining border nodes

---

CHANGELOG.adoc
backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessor.java
frontend/src/workbench/Workbench.tsx
frontend/src/workbench/Workbench.types.ts
frontend/src/workbench/WorkbenchMachine.ts

[377](https://github.com/eclipse-sirius/sirius-components/issues/377)
This PR fixes the issue 377, and restore the refresh of the tab when renaming a representation

[377] Restore rename representation feedback

---

CHANGELOG.adoc
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/IncrementalLayoutEngine.java

https://github.com/eclipse-sirius/sirius-components/issues/868
It computes the position of an edge label if its position is (-1, -1).

[868] Compute the position of an edge label when it does not have any

---

backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/WorkspaceImageDescriptionConverter.java

`EAttributeCustomization.value` is defined as an `InterpretedExpression` in the Sirius Desktop metamodel, and should be interpreted as such.

[865] Fix workspace image path customization

---

frontend/src/diagram/DiagramWebSocketContainerMachine.ts

Signed-off-by: Raphaël Pagé <raphael.page@obeo.fr>
[419](https://github.com/eclipse-sirius/sirius-components/issues/419)
This PR restores the set default tools action, which allows to remember the last tool that was picked in the tool section. This tool is then displayed as the default tool of this section.
...
...
- Create a new Topography diagram
- Create a new Composite Processor
- If you open the tool palette on the new element, the first tool of the left most section is the Composite Processor.
- On the tool palette, select the Data Source tool.
- If you open the tool palette, the first element is now the Data Source tool.

[419] Restore the set default tool action

---

frontend/src/tree/TreeItem.tsx
frontend/src/tree/TreeItemContextMenu.tsx
frontend/src/tree/TreeItemContextMenu.types.ts
frontend/src/tree/TreeItemContextMenuContribution.types.ts

This PR makes the id of the tree accessible from the context menu of the items of the tree.
I am not sure how to test this PR. If you have an idea, please suggest it in the comment

[enh] Add treeId to the context menu props

---

backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/IncrementalLayoutDiagramConverter.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/data/NodeLayoutData.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/NodeSizeProvider.java

Signed-off-by: Charles Wu <camork1@gmail.com>
The border node size  is computed incorrectly during incremental layout process.
The border node no need to add padding size, So this PR remove this padding for border node
Below is the screencast that move a node with three border nodes.
https://user-images.githubusercontent.com/19710731/141887023-3a671316-a85f-431d-8192-d923ccde406b.mov
...

[359] Fix border node's size computation

---

CHANGELOG.adoc
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/EdgeLabelPositionProvider.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/EdgeRoutingPointsProvider.java
frontend/src/diagram/sprotty/siriusMove.ts

https://github.com/eclipse-sirius/sirius-components/issues/425
This PR keeps self-loop edges in place during the move and puts all of them on top.
If there are many self-loop edges, all will be in the same position. (Will be fixed in https://github.com/eclipse-sirius/sirius-components/issues/565)

Fix the position of self-loop edges

---

backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramEventFlux.java
backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/FormEventProcessor.java
backend/sirius-web-spring-collaborative-selection/src/main/java/org/eclipse/sirius/web/spring/collaborative/selection/SelectionEventProcessor.java
backend/sirius-web-spring-collaborative-trees/src/main/java/org/eclipse/sirius/web/spring/collaborative/trees/TreeEventProcessor.java
backend/sirius-web-spring-collaborative-validation/src/main/java/org/eclipse/sirius/web/spring/collaborative/validation/ValidationEventProcessor.java
backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessor.java

Do not attempt to emit payloads on sinks with no subscribers.
Bug: https://github.com/eclipse-sirius/sirius-components/issues/908
...
...
...
...

[908] Fix potential FAIL_ZERO_SUBSCRIBER errors

---

backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/ISiriusWebLayoutConfigurator.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/SiriusWebLayoutConfigurator.java

This avoids breaking the API for existing clients.
Bug: https://github.com/eclipse-sirius/sirius-components/issues/896
...
...
...
...

[896] Add default implementation of the new methods to the interface

---

backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/NodeDescriptionItemProvider.java

Bug: https://github.com/eclipse-sirius/sirius-components/issues/596
...
...
...
...

[596] Fix a regresion which prevented the manual creation of node styles

---

backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DropOnDiagramEventHandler.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeDeleteToolOnDiagramEventHandler.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeEdgeToolOnDiagramEventHandler.java
backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java
backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/DeleteListItemEventHandler.java
backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditCheckboxEventHandler.java
backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditMultiSelectEventHandler.java
backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditRadioEventHandler.java
backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditSelectEventHandler.java
backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditTextfieldEventHandler.java
backend/sirius-web-spring-collaborative-trees/src/main/java/org/eclipse/sirius/web/spring/collaborative/trees/handlers/DeleteTreeItemEventHandler.java
backend/sirius-web-spring-collaborative-trees/src/main/java/org/eclipse/sirius/web/spring/collaborative/trees/handlers/RenameTreeItemEventHandler.java

https://github.com/eclipse-sirius/sirius-components/issues/915
When a handler fails to execute, it uses its returned failure message to create an error payload.
Most of the time when handlers failed to execute, they were returning an _invalid input error_, now the message is empty because all handler failures are created with an empty message.

[915] Use failure messages to create error payload messages

---

CHANGELOG.adoc
frontend/src/diagram/sprotty/DiagramServer.tsx

#925
This PR perform a fit to screen after the first render of a diagram
...
It may happen that some diagrams will have big elements and some others will have small elements depending on diagram bounds are small or big.

[925] Perform a fit to screen after the first render of a diagram

---

frontend/src/diagram/DiagramWebSocketContainer.types.ts
frontend/src/diagram/sprotty/convertDiagram.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/914

[914] Consider that GQLNode#borderNodes and GQLNode#childNodes can be undefined

---

CHANGELOG.adoc
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/ELKDiagramConverter.java

Fix the way we use ELK to layout begin/end labels.
Before:
After:
The PR also removes some `toString()` calls that are redundant now that the corresponding ids are already strings (instead of UUIDs as they were before).

[949] Fix the position of the begin/end labels on edges

---

CHANGELOG.adoc
frontend/src/tree/TreeItem.tsx

Do not render the raw `kind` as we used to do, as it is now more
confusing than anything for the end-user.
For the kinds which are defined by Sirius Components itself, interpret
them to show the same tooltip as before. Default to an empty tooltip
for the others instead of exposing the raw kind value.
---
I'm setting this as "to review soon" because its seems relatively small and safe, but it can be dropped from the release if time is too short.

[878] Fix tooltips for tree items

---

CHANGELOG.adoc
backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java

[enh] Use simple type names for the canonical creation tools

---

frontend/src/diagram/sprotty/DiagramServer.tsx

https://github.com/eclipse-sirius/sirius-components/issues/957
This PR makes sure the fit to screen made when a diagram is opened, is made only when the diagram is opened.
1. Open the diagram
2. Make sure the fit to screen has been made
3. Resize the browser window
4. Make sure the fit to screen has *NOT* been made

[957] Fix the fit to screen triggered by initialize canvas bounds

---

frontend/src/diagram/DiagramWebSocketContainer.tsx
frontend/src/diagram/DiagramWebSocketContainer.types.ts
frontend/src/diagram/sprotty/DiagramServer.tsx
frontend/src/diagram/sprotty/DiagramServer.types.ts

https://github.com/eclipse-sirius/sirius-components/issues/958
Use positions relative to the diagram origin and not positions relative
to the viewport.
It can be using a create edge tool or the connector tool.

[958] Use the right edge start and edge end position

---

frontend/src/diagram/DiagramWebSocketContainer.tsx
frontend/src/diagram/DiagramWebSocketContainer.types.ts
frontend/src/diagram/sprotty/DiagramServer.tsx
frontend/src/diagram/sprotty/DiagramServer.types.ts

closes #958
This PR fixes the connector tool when more than one edge tool can apply.
1. Create a project with a _Domain_ model
2. Create a _Domain_ diagram
3. Create two entities
4. Use the connector tool from the contextual palette to create any kind of relation
The edge should be created and should be correctly positioned.

[958] Fix connector tools when more than one tool can apply

---

backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/EdgeLabelPositionProvider.java
backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/EdgeRoutingPointsProvider.java

https://github.com/eclipse-sirius/sirius-components/issues/948
This PR fixes the edge label positioning for self-loop edges.
1. Create a project with a domain
2. Create a _Domain_ diagram
3. Create an _Entity_
4. Create an edge from the entity to itself
- The edge should be visible
- The edge label should be well-positioned

[948] Fix edge label positioning

---

backend/sirius-components-starter/src/main/java/org/eclipse/sirius/components/starter/SiriusWebStarterConfiguration.java

Fix un-renamed packages in [#808](https://github.com/eclipse-sirius/sirius-components/issues/808)

[releng] Fix package name in the sirius-components-starter

---

CHANGELOG.adoc
backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/view/ViewValidator.java

Make ViewValidator a little less strict. There is no reason to prevent
the creation of views on plain/classical EPackages. From the
ViewConverter point of view, where an EPackage comes from/how it was
created should not matter (if it does, it's a bug in the ViewConverter
part).
Bug: https://github.com/eclipse-sirius/sirius-components/issues/992
...
...
...
...

[992] Accept static domain types

---

backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/compatibility/operations/CreateInstanceOperationHandlerTests.java
backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/compatibility/operations/CreateViewOperationHandlerTests.java
backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/compatibility/operations/DeleteViewOperationHandlerTests.java

[cleanup] Use the existing EditingDomainFactory in tests

---

backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls

Bug: https://github.com/eclipse-sirius/sirius-components/issues/988

[988] Make the newSelection field optional

---

CHANGELOG.adoc
frontend/src/diagram/DiagramWebSocketContainer.tsx
frontend/src/diagram/DiagramWebSocketContainer.types.ts
frontend/src/diagram/sprotty/DiagramServer.tsx
frontend/src/diagram/toolServices.ts

closes https://github.com/eclipse-sirius/sirius-components/issues/991
This PR fixes the edge creation tools feedback.
Also, it adds some type checking.

[991] Fix edge creation tools feedback

---

CHANGELOG.adoc
backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/EdgeComponent.java

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1054

[1054] Add missing variables to compute the label of an edge

---

CHANGELOG.adoc
frontend/src/tree/DiagramTreeItemContextMenuContribution.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1056

[1056] Fix an issue with invalid forwardRef usage

---

CHANGELOG.adoc
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/provider/NodePositionProvider.java
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/updater/ContainmentUpdater.java
backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodeCreationTests.java
backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodePositionProviderTests.java
backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodeResizeTests.java
backend/sirius-components-diagrams-layout/src/test/resources/editing-contexts/testNodeCreation
backend/sirius-components-diagrams-layout/src/test/resources/editing-contexts/testNodeCreationOutsideItsParent
backend/sirius-components-diagrams-layout/src/test/resources/editing-contexts/testResizeWithNoPositionDelta
backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/NodeAssert.java

Bugs: https://github.com/eclipse-sirius/sirius-components/issues/962 , https://github.com/eclipse-sirius/sirius-components/issues/1051
- If a parent node has been previously resized, it is not resized again when creating a child not contained by its bounds.
- When the position of the event creating a child node is outside the parent node boundaries, the parent node is resized.
This PR fixes this issues and provide new tests to detect them.
...
...

[962] [1051] Fix various node resize issues when creating a child node

---

CHANGELOG.adoc
frontend/src/tree/TreeItem.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1062

[1062] Allow expand/collapse of tree items without selecting them

---

frontend/src/tree/TreeItem.tsx

Make sure there is always the same number of children element inside the tree item's main div so the layout is the same whether or not the item has children.
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1063
#1063 
This fixes a regression introduced in https://github.com/eclipse-sirius/sirius-components/commit/48913d175c88a80d0dc10fd16f51a149bcaeee58 where tree items without children (and thus without the collaps/expand arrow) were no longer properly aligned with the others:

[1063] Fix layout regression on tree items without children

---

CHANGELOG.adoc
backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1073

[1073] Add missing error callback on the canBeDisposed subscriber

---

CHANGELOG.adoc
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/IncrementalLayoutEngine.java
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/utils/Geometry.java
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/utils/PointOnRectangleInfo.java
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/utils/RectangleSide.java
backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/BorderNodePositionTests.java

back-end
Bug: https://github.com/eclipse-sirius/sirius-components/issues/919
Signed-off-by: Laurent Fasani <laurent.fasani@obeo.fr>
...
...
...
...

[919] Support the parent container resize for the border nodes on the backend

---

CHANGELOG.adoc
frontend/src/diagram/sprotty/siriusDragAndDropMouseListener.ts

When moving twice the side of a node without moving the cursor between
the two resizes, the second resize kept the initial size of the node.
Now, at mouseUp event,  we recompute the ResizeAction properly.
Signed-off-by: Laurent Fasani <laurent.fasani@obeo.fr>
- [X ] Bug fix
...
...
...
...

[fix] Fix the resize when resizing twice

---

CHANGELOG.adoc
backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/export/svg/DiagramElementExportService.java
backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditTextfieldEventHandler.java
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ELKDiagramConverter.java
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ELKLayoutedDiagramProvider.java
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/IncrementalLayoutEngine.java
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/provider/NodeLabelPositionProvider.java
backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodeLabelPositionProviderTests.java
backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DiagramELKLayoutTest.java
backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/TestDiagramCreationService.java
backend/sirius-components-diagrams-layout/src/test/resources/editing-contexts/testNodeLayoutWithMultilineLabel
backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/TextBoundsProvider.java
backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/LabelType.java
backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/compatibility/properties/EStringIfDescriptionProvider.java
backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/Textarea.java
backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/renderer/FormElementFactory.java
frontend/src/diagram/sprotty/DependencyInjection.ts
frontend/src/diagram/sprotty/Diagram.types.ts
frontend/src/diagram/sprotty/DiagramServer.tsx
frontend/src/diagram/sprotty/EditLabelUIWithInitialContent.ts
frontend/src/diagram/sprotty/views/LabelView.tsx
frontend/src/properties/propertysections/TextfieldPropertySection.tsx

- [ X ] New feature or improvement
...
...
...
...

[781] Add support for multiline labels

---

backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/CompatibilityToolSectionsProvider.java
backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/view/diagram/ViewToolSectionsProvider.java

Fixes: https://github.com/eclipse-sirius/sirius-components/issues/1096
This PR adds the direct edit tool the representations edges.
Before :
After : 
The provider actually fixing this bug is the CompatibilityToolSectionsProvider. The same bug was present on the VewToolSectionsProvider so I fixed it as well, but I am not sure how to test this one. When is it supposed to be called?

[1096] Add direct edit tool to edges

---

frontend/src/diagram/sprotty/EditLabelUIWithInitialContent.ts

When the zoom is too low, a scroll bar appears in the label edit area in diagram 
It enlarge initial label edit area in diagram to avoid the scroll bar
It works with small and large zoom
Diagram Edition - Direct edit

[1097] Update the label edit initial area to avoid the scroll bar 

---

CHANGELOG.adoc
backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/compatibility/diagrams/ToolImageProvider.java
backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/compatibility/diagrams/ToolImageProviderTests.java

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1075
Unlike many others concept in the odesign, OperationAction handles
custom icon through the icon property instead of the iconPath property.
Update ToolImageProvider to also handles icon property in addtion to
iconPath property.

[1075] Use the proper icon feature for OperationAction

---

CHANGELOG.adoc
frontend/src/tree/TreeItem.tsx
frontend/src/tree/TreeItemContextMenu.tsx
frontend/src/tree/TreeItemContextMenu.types.ts

Fix: https://github.com/eclipse-sirius/sirius-components/issues/1067
This PR should hide the hamburger item on menu items who do not have any associated operations. I could not really test it since I do not think that I can reproduce this situation on either OCP or Sirius web.
I am not entirely sure that the condition describing this situation is enough : 
`  const shouldDisplayMoreButton = (item.deletable || item.editable) && treeItemMenuContributionComponents.length > 0;
` 
For example, if an item have different operations but all of them are disabled for some reason, should we still display the hamburger?

[1067] Hide hamburger menu on tree items with no operations

---

backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/ObjectService.java

Signed-off-by: Laurent Fasani <laurent.fasani@obeo.fr>
The icon of the node and listen item of Domain diagram are not displayed
In dev mode we compute the iconURL properly

[fix] Fix the iconURL computation in development mode

---

CHANGELOG.adoc
frontend/src/workbench/Workbench.tsx
frontend/src/workbench/WorkbenchMachine.ts

- [1128] Select the representation opened from a tab
- [1128] Remove dead code in the workbench's state machine
There might be more "aggressive" cleanups/refactoring possible, but given that we approach the release I prefered limiting the impacts.

Select representation opened from a tab

---

backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/view/diagram/NodeStylePropertiesConfigurer.java

CheckStyle 9.3 raises a ParameterAssignmentCheck error here.
...
...
...
...

[cleanup] Fix CheckStyle error

---

CHANGELOG.adoc
frontend/src/diagram/sprotty/DiagramServer.tsx
frontend/src/diagram/sprotty/DiagramServer.types.ts

closes https://github.com/eclipse-sirius/sirius-components/issues/1154
This PR takes the position of the mouse when the click is made, then this position is given to the action that will display the contextual palette.

[1154] Display the palette where the click has been made

---

CHANGELOG.adoc
doc/adrs/053_add_support_for_form_descriptions_in_the_view_converter.adoc

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1152
Signed-off-by: Florian Barbin <florian.barbin@obeo.fr>
#1152 
...
Add the ADR for the support for form descriptions in the view converter
...
...
...

[doc] Add ADR for form descriptions in the view converter support

---

CHANGELOG.adoc
backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/BorderNodesOnSide.java
backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/view/diagram/ViewDiagramDescriptionConverter.java
backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/view/diagram/ViewDiagramDescriptionConverterContext.java
backend/sirius-components-tests/src/main/java/org/eclipse/sirius/components/tests/architecture/AbstractCodingRulesTests.java

ViewDiagramDescriptionConverter is now a service but two attributes
convertedNodes and convertedEdges were mutable and used during the
conversion.
This issue has been detected from this …

[1176] Fix Exception in ViewDiagramDescriptionConverter

---

backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/EdgeMappingConverter.java

This is detected as en error by the new Eclipse CheckStyle 10.0 plug-in.

[cleanup] Add missing whitespace

---

CHANGELOG.adoc
frontend/src/workbench/Site.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1171
https://user-images.githubusercontent.com/10608/164465578-9d10e955-e55a-493c-8a65-b0ac249e2fb6.mp4
_Please describe …

[1171] Fix overflow behavior when side panels are resized

---

CHANGELOG.adoc
backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/DiagramComponent.java
backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponentProps.java
backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/UnsynchronizedDiagramTests.java
backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/view/diagram/ViewDiagramDescriptionConverter.java

Bug: #689
Signed-off-by: Nicolas Vannier <nicolas.vannier@obeo.fr>
#689 
- Implementations of `IObjectService` must now implement `getObjects` in addition of current `getObject`
- Added variable containing objects ids to render for unsynchronized nodes rendering, improving performance
- Added specific semantic elements provider for unsynchronized nodes for converted diagram descriptions
- [] I have read CONTRIBUTING carefully.
- [] I have signed the [Contributor License Agreement](http://www.eclipse.org/legal/CLA.php).
- [] All my commits are signed-off (`-s`) with my mail address of my Eclipse Account.
- [] I have covered my changes by unit tests or integration tests or manual tests.
- [] All tests pass.
- [] I have updated the documentation accordingly

[689] Improve the performances of the unsynchronized nodes

---

CHANGELOG.adoc
frontend/src/formdescriptioneditor/FormDescriptionEditorWebSocketContainer.tsx
frontend/src/formdescriptioneditor/WidgetEntry.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1245 …

[1245] Fix FormDescriptionEditor: drop widget opens new tab on Firefox

---

README.adoc

`npx run turbo` would try to (install and) execute `https://www.npmjs.com/package/run`.

[doc] Fix turbo invocation command in README

---

CHANGELOG.adoc
packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1250
Signed-off-by: Nicolas Vannier <nicolas.vannier@obeo.fr>
the useEffect hooks evaluating …

[1250] Fixed invoke tool effect hooks dependencies

---

CHANGELOG.adoc
packages/diagrams/frontend/sirius-components-diagrams/src/droparea/DropArea.tsx
packages/diagrams/frontend/sirius-components-diagrams/src/droparea/DropArea.types.ts
packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1269
Signed-off-by: Nicolas Vannier <nicolas.vannier@obeo.fr>
Set a diagram in a readonly state and try to drop an element …

[1269] Prevent dropping elements in a read only diagram

---

CHANGELOG.adoc
packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.tsx

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1284 …

[1284] Remove tab when Form representation contains only one page

---

CHANGELOG.adoc
packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DropOnDiagramEventHandler.java
packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandler.java

- [doc] Add ADR-067 on injecting platform services/beans into Java service classes
- [1318] Use auto-wired instances for the Java services used by studios
- [1320] Ensure selectedNode variable is always defined
This section is not relevant if your contribution does not come with …

[1320] Ensure selectedNode variable is always defined

---

CHANGELOG.adoc
packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java

- [doc] Add ADR-067 on injecting platform services/beans into Java service classes
- [1318] Use auto-wired instances for the Java services used by studios
- [1320] Ensure selectedNode variable is always defined
- [1329] Expose convertedNodes variable in all tools' context
This …

Expose convertedNodes variable in all tools' context

---

CHANGELOG.adoc
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormEventProcessor.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormEventProcessorFactory.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/PropertiesEventProcessorFactory.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/RelatedElementsEventProcessorFactory.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/RepresentationsEventProcessorFactory.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/api/IFormEventHandler.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/dto/RenameFormInput.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/handlers/DeleteListItemEventHandler.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditCheckboxEventHandler.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditMultiSelectEventHandler.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditRadioEventHandler.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditSelectEventHandler.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditTextfieldEventHandler.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/handlers/PushButtonEventHandler.java
packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/handlers/RenameFormEventHandler.java
packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/FormEventProcessorTests.java
packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditCheckboxEventHandlerTests.java
packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditMultiSelectEventHandlerTests.java
packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditRadioEventHandlerTests.java
packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditSelectEventHandlerTests.java
packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditTextfieldEventHandlerTests.java
packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/handlers/ListItemEventHandlersTests.java
packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/handlers/PushButtonEventHandlerTests.java
packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/handlers/RenameFormEventHandlerTests.java
packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/Form.java

Bug: https://github.com/eclipse-sirius/sirius-components/issues/457 …

[457] Fix rename Form representation from the project explorer

---

CHANGELOG.adoc
packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/FormDescriptionEditorEventProcessor.java
packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/dto/RenameFormDescriptionEditorInput.java
packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/RenameFormDescriptionEditorEventHandler.java
packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/RenameFormDescriptionEditorEventHandlerTests.java

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1354 …

[1354] Fix rename FormDescriptionEditor from the project explorer
